slogo_team03: slogo.backend.evaluation.IExecutionContext Interface Reference
slogo.backend.evaluation.IExecutionContext Interface Reference
Public Member Functions
Map< String, ITurtleStatus > turtles ()
Map< String, String > environment ()
Map< String, ISyntaxNode > userDefinedCommands ()
Detailed Description
The read-only state of a Logo simulation at a particular time
Definition at line 15 of file IExecutionContext.java.
Member Function Documentation
Map<String, String> slogo.backend.evaluation.IExecutionContext.environment ()
A general place to put configuration variables, akin to a shell's environment. This can be used to store a return value, for example.
Returns
a key-value Map that represents the list of configuration variables
Implemented in slogo.backend.impl.evaluation.ExecutionContext.
Referenced by slogo.View.executeCommand(), slogo.backend.impl.evaluation.commands.Constant.executeRaw(), slogo.backend.impl.evaluation.commands.control.MakeVariable.executeRaw(), slogo.backend.impl.evaluation.commands.multipleturtle.Turtles.executeRaw(), slogo.backend.impl.evaluation.commands.Variable.executeRaw(), slogo.backend.impl.evaluation.commands.MathOperation.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.ExecutionContext.ExecutionContext(), slogo.backend.impl.evaluation.commands.Operation.getContextReturnedVariableName(), slogo.backend.impl.evaluation.commands.Operation.getContextReturnValue(), slogo.backend.impl.evaluation.commands.control.LoopOperation.loop(), slogo.backend.test.OperationTest.operate(), slogo.backend.test.EvaluationTest.testEvaluate(), slogo.backend.test.BackendTest.testExecute(), slogo.backend.test.OperationTest.testForward(), slogo.backend.test.BackendTest.testID(), slogo.backend.test.BackendTest.testIf(), slogo.backend.test.BackendTest.testIfElse(), slogo.backend.test.BackendTest.testMake(), slogo.backend.test.OperationTest.testRepeat(), slogo.backend.test.BackendTest.testTo(), and slogo.backend.test.BackendTest.testTurtles().
Map<String, ITurtleStatus> slogo.backend.evaluation.IExecutionContext.turtles ()
Get the turtles on the map
Returns
a map of turtle names to turtle status
Implemented in slogo.backend.impl.evaluation.ExecutionContext.
Referenced by slogo.View.executeCommand(), slogo.backend.impl.evaluation.commands.control.MakeVariable.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.YCoordinate.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.XCoordinate.executeRaw(), slogo.backend.impl.evaluation.commands.multipleturtle.ID.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.IsPenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.IsShowing.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Heading.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.multipleturtle.Tell.executeRaw(), slogo.backend.impl.evaluation.commands.multipleturtle.Ask.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), slogo.backend.impl.evaluation.ExecutionContext.ExecutionContext(), slogo.backend.impl.evaluation.commands.control.LoopOperation.loop(), slogo.backend.test.BackendTest.testAsk(), slogo.backend.test.BackendTest.testDoTimes(), slogo.backend.test.BackendTest.testFor(), slogo.backend.test.OperationTest.testForward(), slogo.backend.test.OperationTest.testHideTurtle(), slogo.backend.test.BackendTest.testRepeat(), slogo.backend.test.OperationTest.testRepeat(), and slogo.backend.test.BackendTest.testTell().
Map<String, ISyntaxNode> slogo.backend.evaluation.IExecutionContext.userDefinedCommands ()
A place for commands that the user defines; the commands are stored in the tree representation created in parsing
Returns
The list of user-defined commands
Implemented in slogo.backend.impl.evaluation.ExecutionContext.
Referenced by slogo.backend.impl.evaluation.commands.control.MakeVariable.executeRaw(), slogo.backend.impl.evaluation.ExecutionContext.ExecutionContext(), and slogo.backend.impl.evaluation.commands.control.LoopOperation.loop().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/evaluation/IExecutionContext.java