slogo_team03: slogo.UI.ColorSelectorCreator Class Reference
slogo.UI.ColorSelectorCreator Class Reference
Public Member Functions
ColorSelectorCreator (Group root)
Protected Member Functions
ColorPicker getSelector ()
void setUpSelector (String prompt, int width, int height, double d, Color c)
VBox createSelectorWithLabel (String s, int fontsize, Color color)
Private Attributes
ColorPicker myColorSelector
Group myRoot
Detailed Description
Definition at line 9 of file ColorSelectorCreator.java.
Constructor & Destructor Documentation
slogo.UI.ColorSelectorCreator.ColorSelectorCreator (Group root)
Definition at line 14 of file ColorSelectorCreator.java.
Member Function Documentation
VBox slogo.UI.ColorSelectorCreator.createSelectorWithLabel (String s, int fontsize, Color color) protected
Definition at line 31 of file ColorSelectorCreator.java.
References slogo.UI.LabelCreator.createLabel().
Referenced by slogo.UI.PathColorSelector.create(), and slogo.UI.BackgroundColorSelector.create().
ColorPicker slogo.UI.ColorSelectorCreator.getSelector () protected
Definition at line 19 of file ColorSelectorCreator.java.
References slogo.UI.ColorSelectorCreator.myColorSelector.
Referenced by slogo.UI.PathColorSelector.create(), and slogo.UI.BackgroundColorSelector.create().
void slogo.UI.ColorSelectorCreator.setUpSelector (String prompt, int width, int height, double d, Color c) protected
Definition at line 23 of file ColorSelectorCreator.java.
Referenced by slogo.UI.PathColorSelector.create(), and slogo.UI.BackgroundColorSelector.create().
Member Data Documentation
ColorPicker slogo.UI.ColorSelectorCreator.myColorSelector private
Definition at line 11 of file ColorSelectorCreator.java.
Referenced by slogo.UI.ColorSelectorCreator.getSelector().
Group slogo.UI.ColorSelectorCreator.myRoot private
Definition at line 12 of file ColorSelectorCreator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/ColorSelectorCreator.java