slogo_team03: slogo.UI.MethodRunner Class Reference
slogo.UI.MethodRunner Class Reference
Public Member Functions
MethodRunner (Group root, Canvas canvas, List< Turtle > turtleList, List< Line > list, ModuleCreationHelper MCH)
void changeTurtle ()
void setTurtleStatus (String id, ITurtleStatus TS)
void setEnvironment (String var)
void changeEnvironment ()
Private Member Functions
void setTurtleVisibility ()
void moveTurtle ()
boolean redrawIfInScene (ILine l, Line line)
void drawNewLine (ILine l)
void drawLinesUsingToroidal ()
void setTurtleDirection ()
boolean setPenState ()
void setPenAttributes ()
void setPenColor ()
void setPenThickness ()
void setTurtleImage ()
void setBackgroundColor ()
Private Attributes
List< Turtle > turtleList
Canvas canvas
Group root
List< Line > pathList
Turtle turtle
List< ILine > allILines
String ID
ITurtleStatus TS
String environment
ModuleCreationHelper MCH
Detailed Description
This class takes the returns from the backend and updates the user display, including the turtles and the variables that the user sees
Author
Eric Chen
Michael Deng
Michael Ren Nick Widmaier
Definition at line 27 of file MethodRunner.java.
Constructor & Destructor Documentation
slogo.UI.MethodRunner.MethodRunner (Group root, Canvas canvas, List< Turtle > turtleList, List< Line > list, ModuleCreationHelper MCH)
construct a new methodrunner to update our gui
Parameters
root the root
canvas the canvas where the turtle lies
turtleList list of all our turtles created
list list of all lines drawn on the seen
MCH our class holding all our ui elements
Definition at line 55 of file MethodRunner.java.
References slogo.UI.MethodRunner.canvas, slogo.UI.MethodRunner.MCH, slogo.UI.MethodRunner.root, and slogo.UI.MethodRunner.turtleList.
Member Function Documentation
void slogo.UI.MethodRunner.changeEnvironment ()
Definition at line 324 of file MethodRunner.java.
References slogo.UI.ModuleCreationHelper.setUserVariable().
Referenced by slogo.View.executeEnvironmentCommands().
void slogo.UI.MethodRunner.changeTurtle ()
updates the appropriate turtle takes the turtlestatus and checks if any turtles have the same id, otherwise makes a new turtle then sets all the turtle attributes from the backend returns
Definition at line 75 of file MethodRunner.java.
References slogo.UI.Turtle.getThickness(), slogo.UI.ModuleCreationHelper.getTurtleList(), slogo.backend.util.ICoordinates.getX(), slogo.UI.AppConstants.INITIAL_TURTLE_X_POS, slogo.UI.AppConstants.INITIAL_TURTLE_Y_POS, slogo.backend.util.ITurtleStatus.isActive(), slogo.UI.MethodRunner.moveTurtle(), slogo.UI.MethodRunner.setBackgroundColor(), slogo.UI.ModuleCreationHelper.setListViewVariables(), slogo.UI.MethodRunner.setPenAttributes(), slogo.UI.MethodRunner.setPenState(), slogo.UI.Turtle.setShapesMap(), slogo.UI.MethodRunner.setTurtleDirection(), slogo.UI.MethodRunner.setTurtleVisibility(), slogo.backend.util.IDirection.toDegrees(), slogo.backend.util.ITurtleStatus.turtleDirection(), and slogo.backend.util.ITurtleStatus.turtlePosition().
Referenced by slogo.View.executeTurtleCommands().
void slogo.UI.MethodRunner.drawLinesUsingToroidal () private
Definition at line 220 of file MethodRunner.java.
References slogo.UI.ToroidalHelper.makeLinesToroidal().
Referenced by slogo.UI.MethodRunner.moveTurtle().
void slogo.UI.MethodRunner.drawNewLine (ILine l) private
if it's not in the scene, we draw is based on the conditions supplied from the backend
Parameters
l the current Iline in the TurtleStatus line sequence
Definition at line 194 of file MethodRunner.java.
References slogo.UI.AppConstants.BOLD_SIZE, slogo.UI.AppConstants.DASH_SIZE, slogo.backend.util.ILine.end(), slogo.UI.Turtle.getLineProperty(), slogo.UI.Turtle.getThickness(), slogo.backend.util.ICoordinates.getX(), slogo.backend.util.ICoordinates.getY(), slogo.UI.AppConstants.INITIAL_TURTLE_X_POS, slogo.UI.AppConstants.INITIAL_TURTLE_Y_POS, slogo.UI.AppConstants.MAX_PATH_WIDTH, slogo.backend.util.ILine.start(), slogo.backend.impl.util.Qualities.toColor(), and slogo.backend.util.ITurtleStatus.turtleQualities().
Referenced by slogo.UI.MethodRunner.moveTurtle().
void slogo.UI.MethodRunner.moveTurtle () private
Moves turtle to the appropriate position based on turtle status draws the lines behind it if the pen is down
Definition at line 127 of file MethodRunner.java.
References slogo.backend.util.PenState.DOWN, slogo.UI.MethodRunner.drawLinesUsingToroidal(), slogo.UI.MethodRunner.drawNewLine(), slogo.backend.util.ITurtleStatus.lineSequence(), slogo.UI.Turtle.moveTurtle(), slogo.backend.util.ITurtleStatus.penState(), and slogo.UI.MethodRunner.redrawIfInScene().
Referenced by slogo.UI.MethodRunner.changeTurtle().
boolean slogo.UI.MethodRunner.redrawIfInScene (ILine l, Line line) private
If a line with the same properties as the ILine exists in the scene, redraw it Done so that we keep lines drawn from previous commands
Parameters
l ILine in the line sequence provided from the backend
line in the scene based on previous pathlist
Returns
true if already in the scene
Definition at line 167 of file MethodRunner.java.
References slogo.backend.util.ILine.end(), slogo.backend.util.ICoordinates.getX(), slogo.backend.util.ICoordinates.getY(), slogo.UI.AppConstants.INITIAL_TURTLE_X_POS, slogo.UI.AppConstants.INITIAL_TURTLE_Y_POS, slogo.UI.AppConstants.ROUNDING_ERROR, and slogo.backend.util.ILine.start().
Referenced by slogo.UI.MethodRunner.moveTurtle().
void slogo.UI.MethodRunner.setBackgroundColor () private
Changes the background color to be whatever value is given from the TurtleStatus
Definition at line 313 of file MethodRunner.java.
References slogo.backend.impl.util.Qualities.backgroundColor, slogo.UI.AppConstants.CANVAS_HEIGHT, slogo.UI.AppConstants.CANVAS_WIDTH, slogo.UI.ModuleCreationHelper.getBackgroundColorSelector(), slogo.UI.ModuleCreationHelper.getCanvas(), slogo.UI.BackgroundColorSelector.getValue(), slogo.UI.BackgroundColorSelector.setValue(), and slogo.backend.util.ITurtleStatus.turtleQualities().
Referenced by slogo.UI.MethodRunner.changeTurtle().
void slogo.UI.MethodRunner.setEnvironment (String var)
Definition at line 320 of file MethodRunner.java.
Referenced by slogo.View.executeEnvironmentCommands().
void slogo.UI.MethodRunner.setPenAttributes () private
Sets all attributes of the pen
Definition at line 261 of file MethodRunner.java.
References slogo.UI.MethodRunner.setPenColor(), slogo.UI.MethodRunner.setPenThickness(), and slogo.UI.MethodRunner.setTurtleImage().
Referenced by slogo.UI.MethodRunner.changeTurtle().
void slogo.UI.MethodRunner.setPenColor () private
Sets the Pen Color, based off value from TurtleStatus Updates the selector as well
Definition at line 271 of file MethodRunner.java.
References slogo.UI.ModuleCreationHelper.getPathColorSelector(), slogo.UI.PathColorSelector.getValue(), slogo.UI.Turtle.setColor(), slogo.UI.PathColorSelector.setValue(), slogo.backend.impl.util.Qualities.toColor(), and slogo.backend.util.ITurtleStatus.turtleQualities().
Referenced by slogo.UI.MethodRunner.setPenAttributes().
boolean slogo.UI.MethodRunner.setPenState () private
Used to update the Variables ListView displayed to the user
Returns
true if pen is down, false if pen is up
Definition at line 243 of file MethodRunner.java.
References slogo.backend.util.PenState.DOWN, and slogo.backend.util.ITurtleStatus.penState().
Referenced by slogo.UI.MethodRunner.changeTurtle().
void slogo.UI.MethodRunner.setPenThickness () private
Sets the pen thickness, based off value from TurtleStatus This is a value between 1 and 15
Definition at line 280 of file MethodRunner.java.
References slogo.UI.Turtle.getThickness(), slogo.UI.AppConstants.MAX_PATH_WIDTH, slogo.UI.Turtle.setThickness(), slogo.backend.impl.util.Qualities.thickness(), and slogo.backend.util.ITurtleStatus.turtleQualities().
Referenced by slogo.UI.MethodRunner.setPenAttributes().
void slogo.UI.MethodRunner.setTurtleDirection () private
set the turtle orientation
Definition at line 234 of file MethodRunner.java.
References slogo.UI.AppConstants.ORIENTATION_OFFSET, slogo.UI.Turtle.setOrientation(), slogo.backend.util.IDirection.toDegrees(), and slogo.backend.util.ITurtleStatus.turtleDirection().
Referenced by slogo.UI.MethodRunner.changeTurtle().
void slogo.UI.MethodRunner.setTurtleImage () private
Sets the image based off the index returned from the TurtleStatus index is val user put in for command "SetShape val"
Definition at line 291 of file MethodRunner.java.
References slogo.UI.Turtle.getImageName(), slogo.UI.TurtleImageSelector.getItems(), slogo.UI.ModuleCreationHelper.getTurtleSelector(), slogo.UI.TurtleImageSelector.getValue(), slogo.backend.impl.util.Qualities.index(), slogo.UI.MethodRunner.root, slogo.UI.Turtle.setImage(), slogo.backend.impl.util.Qualities.setIndex(), slogo.UI.TurtleImageSelector.setValue(), and slogo.backend.util.ITurtleStatus.turtleQualities().
Referenced by slogo.UI.MethodRunner.setPenAttributes().
void slogo.UI.MethodRunner.setTurtleStatus (String id, ITurtleStatus TS)
set the turtle status
Parameters
id - the turtle id that should be updated
TS - the turtle status corresponding to this id
Definition at line 253 of file MethodRunner.java.
References slogo.UI.MethodRunner.TS.
Referenced by slogo.View.executeTurtleCommands().
void slogo.UI.MethodRunner.setTurtleVisibility () private
show or hide the turtle based on its visibility status
Definition at line 111 of file MethodRunner.java.
References slogo.UI.Turtle.getImage(), slogo.backend.util.Visibility.INVISIBLE, slogo.backend.util.ITurtleStatus.turtleVisibility(), and slogo.backend.util.Visibility.VISIBLE.
Referenced by slogo.UI.MethodRunner.changeTurtle().
Member Data Documentation
List<ILine> slogo.UI.MethodRunner.allILines private
Definition at line 37 of file MethodRunner.java.
Canvas slogo.UI.MethodRunner.canvas private
Definition at line 30 of file MethodRunner.java.
Referenced by slogo.UI.MethodRunner.MethodRunner().
String slogo.UI.MethodRunner.environment private
Definition at line 42 of file MethodRunner.java.
String slogo.UI.MethodRunner.ID private
Definition at line 39 of file MethodRunner.java.
ModuleCreationHelper slogo.UI.MethodRunner.MCH private
Definition at line 43 of file MethodRunner.java.
Referenced by slogo.UI.MethodRunner.MethodRunner().
List<Line> slogo.UI.MethodRunner.pathList private
Definition at line 33 of file MethodRunner.java.
Group slogo.UI.MethodRunner.root private
Definition at line 31 of file MethodRunner.java.
Referenced by slogo.UI.MethodRunner.MethodRunner(), and slogo.UI.MethodRunner.setTurtleImage().
ITurtleStatus slogo.UI.MethodRunner.TS private
Definition at line 41 of file MethodRunner.java.
Referenced by slogo.UI.MethodRunner.setTurtleStatus().
Turtle slogo.UI.MethodRunner.turtle private
Definition at line 35 of file MethodRunner.java.
List<Turtle> slogo.UI.MethodRunner.turtleList private
Definition at line 29 of file MethodRunner.java.
Referenced by slogo.UI.MethodRunner.MethodRunner().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/MethodRunner.java