slogo_team03: slogo.backend.test.EvaluationTest Class Reference
slogo.backend.test.EvaluationTest Class Reference
Public Member Functions
void testEvaluate ()
Private Member Functions
ISyntaxNode setupTree ()
Detailed Description
Definition at line 25 of file EvaluationTest.java.
Member Function Documentation
ISyntaxNode slogo.backend.test.EvaluationTest.setupTree () private
Definition at line 27 of file EvaluationTest.java.
References slogo.backend.parsing.ISyntaxNode.children().
Referenced by slogo.backend.test.EvaluationTest.testEvaluate().
void slogo.backend.test.EvaluationTest.testEvaluate ()
Definition at line 46 of file EvaluationTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.backend.evaluation.IEvaluator.evaluate(), slogo.Constants.RETURN_VALUE_ENVIRONMENT, and slogo.backend.test.EvaluationTest.setupTree().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/test/EvaluationTest.java