slogo_team03: slogo.frontend.Config.ParameterDistributor Class Reference
slogo.frontend.Config.ParameterDistributor Class Reference
Public Member Functions
ParameterDistributor readConfigHashMap (Map< String, String > map)
Map< String, Integer > getVariableMap ()
Map< String, Color > getColorMap ()
int getNumOfTurtles ()
Public Attributes
int numOfTurtles
Package Attributes
Map< String, String > configMap = new HashMap<String, String>()
Map< String, Integer > variableMap = new HashMap<String, Integer>()
Map< String, Color > colorMap = new HashMap<String, Color>()
Private Member Functions
void distributeVariables (String s)
Detailed Description
NOT FULLY IMPLEMENTED OR COMPLETED. NOT REPRESENTATIVE OF THE REST OF THE PROJECT
Author
Michael Deng
Definition at line 16 of file ParameterDistributor.java.
Member Function Documentation
void slogo.frontend.Config.ParameterDistributor.distributeVariables (String s) private
Definition at line 32 of file ParameterDistributor.java.
Referenced by slogo.frontend.Config.ParameterDistributor.readConfigHashMap().
Map<String, Color> slogo.frontend.Config.ParameterDistributor.getColorMap ()
Definition at line 56 of file ParameterDistributor.java.
References slogo.frontend.Config.ParameterDistributor.colorMap.
Referenced by slogo.UI.ModuleCreationHelper.activateLoadButton().
int slogo.frontend.Config.ParameterDistributor.getNumOfTurtles ()
Definition at line 60 of file ParameterDistributor.java.
References slogo.frontend.Config.ParameterDistributor.numOfTurtles.
Referenced by slogo.UI.ModuleCreationHelper.activateLoadButton().
Map<String, Integer> slogo.frontend.Config.ParameterDistributor.getVariableMap ()
Definition at line 52 of file ParameterDistributor.java.
References slogo.frontend.Config.ParameterDistributor.variableMap.
Referenced by slogo.UI.ModuleCreationHelper.activateLoadButton().
ParameterDistributor slogo.frontend.Config.ParameterDistributor.readConfigHashMap (Map< String, String > map)
Definition at line 24 of file ParameterDistributor.java.
References slogo.frontend.Config.ParameterDistributor.distributeVariables().
Referenced by slogo.frontend.Config.ConfigReader.readFile().
Member Data Documentation
Map<String, Color> slogo.frontend.Config.ParameterDistributor.colorMap = new HashMap<String, Color>() package
Definition at line 21 of file ParameterDistributor.java.
Referenced by slogo.frontend.Config.ParameterDistributor.getColorMap().
Map<String, String> slogo.frontend.Config.ParameterDistributor.configMap = new HashMap<String, String>() package
Definition at line 18 of file ParameterDistributor.java.
int slogo.frontend.Config.ParameterDistributor.numOfTurtles
Definition at line 22 of file ParameterDistributor.java.
Referenced by slogo.frontend.Config.ParameterDistributor.getNumOfTurtles().
Map<String, Integer> slogo.frontend.Config.ParameterDistributor.variableMap = new HashMap<String, Integer>() package
Definition at line 20 of file ParameterDistributor.java.
Referenced by slogo.frontend.Config.ParameterDistributor.getVariableMap().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/frontend/Config/ParameterDistributor.java