slogo_team03: slogo.UI.TurtleImageSelector Class Reference
slogo.UI.TurtleImageSelector Class Reference
Public Member Functions
TurtleImageSelector (VBox selectorsVBox)
ObservableList< String > getItems ()
void setValue (String s)
String getValue ()
Protected Member Functions
void create (Group root, Turtle turtle, View view)
void updateMap (String s, Image i, List< Turtle > turtleList)
Private Attributes
VBox mySelectorsVBox
List< String > myPossibleImages
ComboBox< String > mySelector
Detailed Description
10/13/2014
Version 1
Author
Michael Deng
Definition at line 24 of file TurtleImageSelector.java.
Constructor & Destructor Documentation
slogo.UI.TurtleImageSelector.TurtleImageSelector (VBox selectorsVBox)
The constructor
Parameters
selectorsVBox The vBox the selector will belong to
Definition at line 35 of file TurtleImageSelector.java.
Member Function Documentation
void slogo.UI.TurtleImageSelector.create (Group root, Turtle turtle, View view) protected
Creates a VBox
Parameters
root The group the VBox will belong to
turtle The turtle
view The view
Definition at line 47 of file TurtleImageSelector.java.
References slogo.UI.SelectorCreator.createSelectorWithLabel(), slogo.UI.SelectorCreator.getSelector(), slogo.UI.Turtle.getShapesMap(), slogo.UI.AppConstants.LABEL_FONT_SIZE, slogo.UI.AppConstants.SELECTOR_FONT_SIZE, slogo.UI.AppConstants.SELECTOR_HEIGHT, slogo.UI.AppConstants.SELECTOR_WIDTH, slogo.View.sendCommandToBackend(), and slogo.UI.SelectorCreator.setUpSelector().
Referenced by slogo.UI.ModuleCreationHelper.createSelectors().
ObservableList<String> slogo.UI.TurtleImageSelector.getItems ()
Gets the items from the list of images
Returns
The list of images
Definition at line 87 of file TurtleImageSelector.java.
Referenced by slogo.UI.MethodRunner.setTurtleImage().
String slogo.UI.TurtleImageSelector.getValue ()
Gets the value of the selector
Returns
The value
Definition at line 105 of file TurtleImageSelector.java.
Referenced by slogo.UI.MethodRunner.setTurtleImage().
void slogo.UI.TurtleImageSelector.setValue (String s)
Sets the value of the selector
Parameters
s The value
Definition at line 96 of file TurtleImageSelector.java.
Referenced by slogo.UI.MethodRunner.setTurtleImage().
void slogo.UI.TurtleImageSelector.updateMap (String s, Image i, List< Turtle > turtleList) protected
Populates the map of turtle images
Parameters
s The new key
iv The image view
turtleList The list of turtles
Definition at line 75 of file TurtleImageSelector.java.
Referenced by slogo.UI.ImageLoader.chooseNewImage().
Member Data Documentation
List<String> slogo.UI.TurtleImageSelector.myPossibleImages private
Definition at line 27 of file TurtleImageSelector.java.
ComboBox<String> slogo.UI.TurtleImageSelector.mySelector private
Definition at line 28 of file TurtleImageSelector.java.
VBox slogo.UI.TurtleImageSelector.mySelectorsVBox private
Definition at line 26 of file TurtleImageSelector.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/TurtleImageSelector.java