slogo_team03: slogo.backend.test.GrammarRuleTest Class Reference
slogo.backend.test.GrammarRuleTest Class Reference
Public Member Functions
void testInfiniteMatchRecurse (boolean expected, String[][] pattern, String[] search)
void testSunny ()
void testSunnyEnd ()
void testExtraPattern ()
void testExtraSearch ()
void testJustOneRepeat ()
void testMatches ()
void testMultiMatches ()
void testDoTimes ()
Detailed Description
Definition at line 17 of file GrammarRuleTest.java.
Member Function Documentation
void slogo.backend.test.GrammarRuleTest.testDoTimes ()
Definition at line 105 of file GrammarRuleTest.java.
References slogo.Constants.CLOSING_LIST_LABEL, slogo.Constants.CONSTANT_LABEL, slogo.Constants.INFINITE_MATCHING_LABEL, slogo.backend.parsing.IGrammarRule.matches(), slogo.Constants.OPENING_LIST_LABEL, and slogo.Constants.VARIABLE_LABEL.
void slogo.backend.test.GrammarRuleTest.testExtraPattern ()
Definition at line 46 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse().
void slogo.backend.test.GrammarRuleTest.testExtraSearch ()
Definition at line 55 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse().
void slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse (boolean expected, String pattern[][], String[] search)
Definition at line 18 of file GrammarRuleTest.java.
References slogo.backend.impl.parsing.GrammarRule.infiniteMatchRecurse().
Referenced by slogo.backend.test.GrammarRuleTest.testExtraPattern(), slogo.backend.test.GrammarRuleTest.testExtraSearch(), slogo.backend.test.GrammarRuleTest.testJustOneRepeat(), slogo.backend.test.GrammarRuleTest.testSunny(), and slogo.backend.test.GrammarRuleTest.testSunnyEnd().
void slogo.backend.test.GrammarRuleTest.testJustOneRepeat ()
Definition at line 64 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse().
void slogo.backend.test.GrammarRuleTest.testMatches ()
Definition at line 73 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.parsing.IGrammarRule.matches().
void slogo.backend.test.GrammarRuleTest.testMultiMatches ()
Definition at line 85 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.parsing.IGrammarRule.matches().
void slogo.backend.test.GrammarRuleTest.testSunny ()
Definition at line 29 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse().
void slogo.backend.test.GrammarRuleTest.testSunnyEnd ()
Definition at line 38 of file GrammarRuleTest.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/test/GrammarRuleTest.java