slogo_team03: slogo.backend.impl.util.Coordinates Class Reference
slogo.backend.impl.util.Coordinates Class Reference
Public Member Functions
Coordinates (double myX, double myY)
Number getX ()
Number getY ()
Number getDistance (ICoordinates c)
Package Attributes
double x
double y
Detailed Description
Definition at line 5 of file Coordinates.java.
Constructor & Destructor Documentation
slogo.backend.impl.util.Coordinates.Coordinates (double myX, double myY)
Definition at line 9 of file Coordinates.java.
Member Function Documentation
Number slogo.backend.impl.util.Coordinates.getDistance (ICoordinates c)
Implements slogo.backend.util.ICoordinates.
Definition at line 25 of file Coordinates.java.
References slogo.backend.util.ICoordinates.getX(), slogo.backend.impl.util.Coordinates.getX(), slogo.backend.util.ICoordinates.getY(), and slogo.backend.impl.util.Coordinates.getY().
Number slogo.backend.impl.util.Coordinates.getX ()
Get the x coordinate
Returns
the x coordinate
Implements slogo.backend.util.ICoordinates.
Definition at line 15 of file Coordinates.java.
References slogo.backend.impl.util.Coordinates.x.
Referenced by slogo.backend.impl.util.Coordinates.getDistance().
Number slogo.backend.impl.util.Coordinates.getY ()
Get the y coordinate
Returns
the y coordinate
Implements slogo.backend.util.ICoordinates.
Definition at line 20 of file Coordinates.java.
References slogo.backend.impl.util.Coordinates.y.
Referenced by slogo.backend.impl.util.Coordinates.getDistance().
Member Data Documentation
double slogo.backend.impl.util.Coordinates.x package
Definition at line 6 of file Coordinates.java.
Referenced by slogo.backend.impl.util.Coordinates.getX().
double slogo.backend.impl.util.Coordinates.y package
Definition at line 7 of file Coordinates.java.
Referenced by slogo.backend.impl.util.Coordinates.getY().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/util/Coordinates.java