slogo_team03: slogo.UI.GridLinesToggler Class Reference
slogo.UI.GridLinesToggler Class Reference
Public Member Functions
GridLinesToggler (VBox vbox)
Protected Member Functions
List< Line > getLinesList ()
void activate (TurtleCanvas myCanvas, Group root)
Private Member Functions
void addLine (Line l)
void removeLines (Group root)
Private Attributes
CheckBox myCheckBox
List< Line > myGridLines
Detailed Description
Definition at line 14 of file GridLinesToggler.java.
Constructor & Destructor Documentation
slogo.UI.GridLinesToggler.GridLinesToggler (VBox vbox)
Definition at line 19 of file GridLinesToggler.java.
References slogo.UI.CheckBoxCreator.createCheckBox().
Member Function Documentation
void slogo.UI.GridLinesToggler.activate (TurtleCanvas myCanvas, Group root) protected
Creates an event handler that makes grid lines on the canvas when fired
Parameters
cb The checkbox that fires the event
Definition at line 34 of file GridLinesToggler.java.
References slogo.UI.GridLinesToggler.addLine(), slogo.UI.TurtleCanvas.getCanvas(), slogo.UI.AppConstants.GRIDLINES_SPACING, and slogo.UI.GridLinesToggler.removeLines().
Referenced by slogo.UI.ModuleCreationHelper.createGridCheckBox().
void slogo.UI.GridLinesToggler.addLine (Line l) private
Definition at line 65 of file GridLinesToggler.java.
Referenced by slogo.UI.GridLinesToggler.activate().
List<Line> slogo.UI.GridLinesToggler.getLinesList () protected
Definition at line 25 of file GridLinesToggler.java.
References slogo.UI.GridLinesToggler.myGridLines.
void slogo.UI.GridLinesToggler.removeLines (Group root) private
Definition at line 70 of file GridLinesToggler.java.
Referenced by slogo.UI.GridLinesToggler.activate().
Member Data Documentation
CheckBox slogo.UI.GridLinesToggler.myCheckBox private
Definition at line 16 of file GridLinesToggler.java.
List<Line> slogo.UI.GridLinesToggler.myGridLines private
Definition at line 17 of file GridLinesToggler.java.
Referenced by slogo.UI.GridLinesToggler.getLinesList().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/GridLinesToggler.java