slogo_team03: slogo.backend.test.OperationTest Class Reference
slogo.backend.test.OperationTest Class Reference
Public Member Functions
void testOperationFactory ()
IExecutionContext buildContext ()
String operate (int flag, IOperation op, String s1, String s2)
void testAnd ()
void testOr ()
void testNot ()
void testLess ()
void testSum ()
void testAtan ()
void testForward ()
void testHideTurtle ()
void testRepeat ()
Detailed Description
Definition at line 47 of file OperationTest.java.
Member Function Documentation
IExecutionContext slogo.backend.test.OperationTest.buildContext ()
Definition at line 68 of file OperationTest.java.
References slogo.backend.util.PenState.DOWN, and slogo.backend.util.Visibility.VISIBLE.
Referenced by slogo.backend.test.OperationTest.operate(), slogo.backend.test.OperationTest.testForward(), slogo.backend.test.OperationTest.testHideTurtle(), and slogo.backend.test.OperationTest.testRepeat().
String slogo.backend.test.OperationTest.operate (int flag, IOperation op, String s1, String s2)
Definition at line 82 of file OperationTest.java.
References slogo.backend.test.OperationTest.buildContext(), slogo.backend.evaluation.IExecutionContext.environment(), and slogo.backend.evaluation.IOperation.execute().
Referenced by slogo.backend.test.OperationTest.testAnd(), slogo.backend.test.OperationTest.testAtan(), slogo.backend.test.OperationTest.testLess(), slogo.backend.test.OperationTest.testNot(), slogo.backend.test.OperationTest.testOr(), and slogo.backend.test.OperationTest.testSum().
void slogo.backend.test.OperationTest.testAnd ()
Definition at line 102 of file OperationTest.java.
References slogo.backend.test.OperationTest.operate().
void slogo.backend.test.OperationTest.testAtan ()
Definition at line 178 of file OperationTest.java.
References slogo.backend.test.OperationTest.operate().
void slogo.backend.test.OperationTest.testForward ()
Definition at line 193 of file OperationTest.java.
References slogo.backend.test.OperationTest.buildContext(), slogo.backend.util.PenState.DOWN, slogo.backend.util.ILine.end(), slogo.backend.evaluation.IExecutionContext.environment(), slogo.backend.evaluation.IOperation.execute(), slogo.backend.util.ICoordinates.getX(), slogo.backend.util.ICoordinates.getY(), slogo.backend.util.ITurtleStatus.lineSequence(), slogo.backend.util.ITurtleStatus.penState(), slogo.backend.util.ILine.start(), slogo.backend.util.IDirection.toDegrees(), slogo.backend.util.ITurtleStatus.turtleDirection(), slogo.backend.util.ITurtleStatus.turtlePosition(), slogo.backend.evaluation.IExecutionContext.turtles(), slogo.backend.util.ITurtleStatus.turtleVisibility(), and slogo.backend.util.Visibility.VISIBLE.
void slogo.backend.test.OperationTest.testHideTurtle ()
Definition at line 248 of file OperationTest.java.
References slogo.backend.test.OperationTest.buildContext(), slogo.backend.evaluation.IOperation.execute(), slogo.backend.util.Visibility.INVISIBLE, and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.OperationTest.testLess ()
Definition at line 148 of file OperationTest.java.
References slogo.backend.test.OperationTest.operate().
void slogo.backend.test.OperationTest.testNot ()
Definition at line 133 of file OperationTest.java.
References slogo.backend.test.OperationTest.operate().
void slogo.backend.test.OperationTest.testOperationFactory ()
Definition at line 49 of file OperationTest.java.
References slogo.backend.evaluation.IOperationFactory.makeElement(), and slogo.backend.evaluation.IOperation.type().
void slogo.backend.test.OperationTest.testOr ()
Definition at line 118 of file OperationTest.java.
References slogo.backend.test.OperationTest.operate().
void slogo.backend.test.OperationTest.testRepeat ()
Definition at line 266 of file OperationTest.java.
References slogo.backend.test.OperationTest.buildContext(), slogo.backend.evaluation.IExecutionContext.environment(), slogo.backend.impl.evaluation.commands.Operation.execute(), slogo.backend.util.ICoordinates.getX(), slogo.backend.util.ICoordinates.getY(), and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.OperationTest.testSum ()
Definition at line 163 of file OperationTest.java.
References slogo.backend.test.OperationTest.operate().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/test/OperationTest.java