slogo_team03: slogo.UI.ListViewAllSLOGO Class Reference
slogo.UI.ListViewAllSLOGO Class Reference abstract
Public Member Functions
ListViewAllSLOGO (Group root)
ListViewAllSLOGO (VBox vBox)
ListViewAllSLOGO createListView (int listViewHeight, int listViewWidth, int vboxXpos, int vboxYpos, String labelName, int fontSize, Color color)
ListViewAllSLOGO createListView (int listViewHeight, int listViewWidth, String labelName, int fontSize, Color color)
Protected Member Functions
ListView< String > getListView ()
void setItems (ObservableList< String > oList)
ObservableList< String > getItems ()
abstract void create ()
Protected Attributes
ListViewCreator myListViewCreator
Private Attributes
Group myRoot
VBox vBox
Detailed Description
10/8/2014
Version 1
Author
Nick Widmaier
Michael Deng
Michael Ren
Eric Chen
Definition at line 22 of file ListViewAllSLOGO.java.
Constructor & Destructor Documentation
slogo.UI.ListViewAllSLOGO.ListViewAllSLOGO (Group root)
Definition at line 28 of file ListViewAllSLOGO.java.
slogo.UI.ListViewAllSLOGO.ListViewAllSLOGO (VBox vBox)
Definition at line 33 of file ListViewAllSLOGO.java.
References slogo.UI.ListViewAllSLOGO.vBox.
Member Function Documentation
abstract void slogo.UI.ListViewAllSLOGO.create () abstract protected
ListViewAllSLOGO slogo.UI.ListViewAllSLOGO.createListView (int listViewHeight, int listViewWidth, int vboxXpos, int vboxYpos, String labelName, int fontSize, Color color)
Definition at line 37 of file ListViewAllSLOGO.java.
References slogo.UI.ListViewCreator.createListViewWithLabel().
Referenced by slogo.UI.ListViewPreviousCommands.create(), slogo.UI.ListViewUserVariables.create(), slogo.UI.ListViewUserCommands.create(), and slogo.UI.ListViewSLOGOVariables.create().
ListViewAllSLOGO slogo.UI.ListViewAllSLOGO.createListView (int listViewHeight, int listViewWidth, String labelName, int fontSize, Color color)
Definition at line 53 of file ListViewAllSLOGO.java.
References slogo.UI.ListViewCreator.createListViewWithLabel().
ObservableList<String> slogo.UI.ListViewAllSLOGO.getItems () protected
Definition at line 75 of file ListViewAllSLOGO.java.
References slogo.UI.ListViewCreator.getListView().
Referenced by slogo.UI.ModuleCreationHelper.activateSaveButton(), slogo.UI.ModuleCreationHelper.activateTurtleCanvas(), slogo.UI.ModuleCreationHelper.clearUserVariables(), and slogo.UI.ModuleCreationHelper.setUserVariable().
ListView<String> slogo.UI.ListViewAllSLOGO.getListView () protected
Definition at line 67 of file ListViewAllSLOGO.java.
References slogo.UI.ListViewCreator.getListView().
void slogo.UI.ListViewAllSLOGO.setItems (ObservableList< String > oList) protected
Definition at line 71 of file ListViewAllSLOGO.java.
References slogo.UI.ListViewCreator.getListView().
Referenced by slogo.UI.ModuleCreationHelper.addToCertainList(), slogo.UI.ModuleCreationHelper.clearCertainList(), slogo.UI.ModuleCreationHelper.resetCommandsHistoryList(), slogo.UI.ModuleCreationHelper.setListViewVariables(), and slogo.UI.ModuleCreationHelper.stepThroughCommandsHistory().
Member Data Documentation
ListViewCreator slogo.UI.ListViewAllSLOGO.myListViewCreator protected
Definition at line 26 of file ListViewAllSLOGO.java.
Referenced by slogo.UI.ListViewSLOGOVariables.create().
Group slogo.UI.ListViewAllSLOGO.myRoot private
Definition at line 24 of file ListViewAllSLOGO.java.
VBox slogo.UI.ListViewAllSLOGO.vBox private
Definition at line 25 of file ListViewAllSLOGO.java.
Referenced by slogo.UI.ListViewAllSLOGO.ListViewAllSLOGO().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/ListViewAllSLOGO.java