slogo_team03: slogo.backend.impl.evaluation.commands.Operation Class Reference
slogo.backend.impl.evaluation.commands.Operation Class Reference abstract
Public Member Functions
Operation (String type, int argMin, int argMax)
IExecutionContext execute (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
String type ()
Protected Member Functions
void validateArguments (List< IExecutionContext > args) throws MalformedSyntaxException
abstract IExecutionContext executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
List< Number > generateNumericArguments (List< IExecutionContext > args)
IExecutionContext mergeContexts (List< IExecutionContext > contexts)
String getContextReturnValue (IExecutionContext context)
String getContextReturnedVariableName (IExecutionContext context)
Private Attributes
String type
int argMin
int argMax
Detailed Description
Super class for all non-math operations
Definition at line 20 of file Operation.java.
Constructor & Destructor Documentation
slogo.backend.impl.evaluation.commands.Operation.Operation (String type, int argMin, int argMax)
Create a new operation
Parameters
type An identifier for this operation
argMin The minimum number of arguments for this operation
argMax The maximum number of arguments for this operation
Definition at line 33 of file Operation.java.
References slogo.backend.impl.evaluation.commands.Operation.argMax, slogo.backend.impl.evaluation.commands.Operation.argMin, and slogo.backend.impl.evaluation.commands.Operation.type().
Member Function Documentation
IExecutionContext slogo.backend.impl.evaluation.commands.Operation.execute (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
Perform the function on a state/context
Parameters
args any arguments needed for the operation
Returns
the new state of the execution
Implements slogo.backend.evaluation.IOperation.
Definition at line 62 of file Operation.java.
References slogo.backend.impl.evaluation.commands.Operation.executeRaw(), and slogo.backend.impl.evaluation.commands.Operation.validateArguments().
Referenced by slogo.backend.test.OperationTest.testRepeat().
abstract IExecutionContext slogo.backend.impl.evaluation.commands.Operation.executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException abstract protected
Process child ExecutionContext and merge them into one single ExecutionContext
Parameters
args,a list of child ExecutionContexts
previous,the previous ExecutionContext
current,the current syntax node
Returns
the merged ExecutionContext
Exceptions
MalformedSyntaxException
Referenced by slogo.backend.impl.evaluation.commands.Operation.execute().
List<Number> slogo.backend.impl.evaluation.commands.Operation.generateNumericArguments (List< IExecutionContext > args) protected
Definition at line 84 of file Operation.java.
References slogo.Constants.RETURN_VALUE_ENVIRONMENT.
Referenced by slogo.backend.impl.evaluation.commands.MathOperation.executeRaw().
String slogo.backend.impl.evaluation.commands.Operation.getContextReturnedVariableName (IExecutionContext context) protected
Get the name of the variable that was returned in the return value, if any
Parameters
context The context to get the returned variable name
Returns
The name of the variable that was returned
Definition at line 124 of file Operation.java.
References slogo.backend.evaluation.IExecutionContext.environment(), and slogo.Constants.RETURNED_VARIABLE_NAME.
Referenced by slogo.backend.impl.evaluation.commands.control.LoopOperation.handleCounterName().
String slogo.backend.impl.evaluation.commands.Operation.getContextReturnValue (IExecutionContext context) protected
Get the string return value representation from a context
Parameters
context The context to get the return value from
Returns
The string representing the return value, or an empty string if no return value exists
Definition at line 110 of file Operation.java.
References slogo.backend.evaluation.IExecutionContext.environment(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
Referenced by slogo.backend.impl.evaluation.commands.control.LoopOperation.handleCountStart(), slogo.backend.impl.evaluation.commands.control.LoopOperation.handleIncrement(), slogo.backend.impl.evaluation.commands.control.ConditionalOperation.kipling(), and slogo.backend.impl.evaluation.commands.control.LoopOperation.loop().
IExecutionContext slogo.backend.impl.evaluation.commands.Operation.mergeContexts (List< IExecutionContext > contexts) protected
Provide a policy for which child context should be promoted to represent the state of the parent
Parameters
contexts A list of candidate child contexts to choose from
Returns
The chosen context
Definition at line 99 of file Operation.java.
Referenced by slogo.backend.impl.evaluation.commands.Result.executeRaw(), slogo.backend.impl.evaluation.commands.Constant.executeRaw(), and slogo.backend.impl.evaluation.commands.MathOperation.executeRaw().
String slogo.backend.impl.evaluation.commands.Operation.type ()
Identifies the type of the operation
Returns
the string that represents the type of the operation
Implements slogo.backend.evaluation.IOperation.
Definition at line 133 of file Operation.java.
Referenced by slogo.backend.impl.evaluation.commands.Operation.Operation(), and slogo.backend.impl.parsing.Parser.tokensToNodes().
void slogo.backend.impl.evaluation.commands.Operation.validateArguments (List< IExecutionContext > args) throws MalformedSyntaxException protected
check for valid number of arguments
Parameters
args
Exceptions
MalformedSyntaxException
Definition at line 45 of file Operation.java.
References slogo.backend.impl.evaluation.commands.Operation.argMin, and slogo.Constants.INFINITE_ARGUMENTS.
Referenced by slogo.backend.impl.evaluation.commands.Operation.execute().
Member Data Documentation
int slogo.backend.impl.evaluation.commands.Operation.argMax private
Definition at line 24 of file Operation.java.
Referenced by slogo.backend.impl.evaluation.commands.Operation.Operation().
int slogo.backend.impl.evaluation.commands.Operation.argMin private
Definition at line 23 of file Operation.java.
Referenced by slogo.backend.impl.evaluation.commands.Operation.Operation(), and slogo.backend.impl.evaluation.commands.Operation.validateArguments().
String slogo.backend.impl.evaluation.commands.Operation.type private
Definition at line 22 of file Operation.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/evaluation/commands/Operation.java