slogo_team03: slogo.backend.util.ICoordinates Interface Reference
slogo.backend.util.ICoordinates Interface Reference
Public Member Functions
Number getX ()
Number getY ()
Number getDistance (ICoordinates c)
Detailed Description
A set of 2D coordinate points
Definition at line 7 of file ICoordinates.java.
Member Function Documentation
Number slogo.backend.util.ICoordinates.getDistance (ICoordinates c)
Implemented in slogo.backend.impl.util.Coordinates.
Referenced by slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), and slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw().
Number slogo.backend.util.ICoordinates.getX ()
Get the x coordinate
Returns
the x coordinate
Implemented in slogo.backend.impl.util.Coordinates.
Referenced by slogo.UI.MethodRunner.changeTurtle(), slogo.UI.MethodRunner.drawNewLine(), slogo.backend.impl.evaluation.commands.turtle.XCoordinate.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.util.Coordinates.getDistance(), slogo.UI.MethodRunner.redrawIfInScene(), slogo.backend.test.OperationTest.testForward(), and slogo.backend.test.OperationTest.testRepeat().
Number slogo.backend.util.ICoordinates.getY ()
Get the y coordinate
Returns
the y coordinate
Implemented in slogo.backend.impl.util.Coordinates.
Referenced by slogo.UI.MethodRunner.drawNewLine(), slogo.backend.impl.evaluation.commands.turtle.YCoordinate.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.util.Coordinates.getDistance(), slogo.UI.MethodRunner.redrawIfInScene(), slogo.backend.test.OperationTest.testForward(), and slogo.backend.test.OperationTest.testRepeat().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/util/ICoordinates.java