slogo_team03: slogo.UI.PathTextureSelector Class Reference
slogo.UI.PathTextureSelector Class Reference
Public Member Functions
PathTextureSelector (VBox vbox)
Protected Member Functions
void create (Group root, Turtle t)
Private Member Functions
void populateLineTextureList (List< String > list)
Private Attributes
VBox myVbox
ComboBox< String > pathTexture
Detailed Description
Definition at line 13 of file PathTextureSelector.java.
Constructor & Destructor Documentation
slogo.UI.PathTextureSelector.PathTextureSelector (VBox vbox)
Definition at line 18 of file PathTextureSelector.java.
Member Function Documentation
void slogo.UI.PathTextureSelector.create (Group root, Turtle t) protected
Definition at line 22 of file PathTextureSelector.java.
References slogo.UI.SelectorCreator.createSelectorWithLabel(), slogo.UI.SelectorCreator.getSelector(), slogo.UI.AppConstants.LABEL_FONT_SIZE, slogo.UI.PathTextureSelector.populateLineTextureList(), slogo.UI.AppConstants.SELECTOR_FONT_SIZE, slogo.UI.AppConstants.SELECTOR_HEIGHT, slogo.UI.AppConstants.SELECTOR_WIDTH, slogo.UI.Turtle.setLineProperty(), and slogo.UI.SelectorCreator.setUpSelector().
Referenced by slogo.UI.ModuleCreationHelper.createSelectors().
void slogo.UI.PathTextureSelector.populateLineTextureList (List< String > list) private
Definition at line 42 of file PathTextureSelector.java.
Referenced by slogo.UI.PathTextureSelector.create().
Member Data Documentation
VBox slogo.UI.PathTextureSelector.myVbox private
Definition at line 15 of file PathTextureSelector.java.
ComboBox<String> slogo.UI.PathTextureSelector.pathTexture private
Definition at line 16 of file PathTextureSelector.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/PathTextureSelector.java