slogo_team03: slogo.frontend.Config.ConfigReader Class Reference
slogo.frontend.Config.ConfigReader Class Reference
Public Member Functions
ConfigReader ()
ParameterDistributor readFile () throws IOException
Private Member Functions
int calculateNumOfLines () throws IOException
void populateTextData (int count, BufferedReader textReader) throws IOException
Map< String, String > hashMapTest ()
Private Attributes
Map< String, String > configMap
String path = "src/slogo/frontend/Config/Config.txt"
ParameterDistributor paramDistributor
Detailed Description
NOT FULLY IMPLEMENTED OR COMPLETED. NOT REPRESENTATIVE OF THE REST OF THE PROJECT
Author
Michael Deng
Definition at line 20 of file ConfigReader.java.
Constructor & Destructor Documentation
slogo.frontend.Config.ConfigReader.ConfigReader ()
Definition at line 26 of file ConfigReader.java.
Member Function Documentation
int slogo.frontend.Config.ConfigReader.calculateNumOfLines () throws IOException private
Definition at line 46 of file ConfigReader.java.
Referenced by slogo.frontend.Config.ConfigReader.readFile().
Map<String, String> slogo.frontend.Config.ConfigReader.hashMapTest () private
Definition at line 66 of file ConfigReader.java.
void slogo.frontend.Config.ConfigReader.populateTextData (int count, BufferedReader textReader) throws IOException private
Definition at line 58 of file ConfigReader.java.
Referenced by slogo.frontend.Config.ConfigReader.readFile().
ParameterDistributor slogo.frontend.Config.ConfigReader.readFile () throws IOException
Definition at line 31 of file ConfigReader.java.
References slogo.frontend.Config.ConfigReader.calculateNumOfLines(), slogo.frontend.Config.ConfigReader.paramDistributor, slogo.frontend.Config.ConfigReader.populateTextData(), and slogo.frontend.Config.ParameterDistributor.readConfigHashMap().
Referenced by slogo.UI.ModuleCreationHelper.activateLoadButton().
Member Data Documentation
Map<String, String> slogo.frontend.Config.ConfigReader.configMap private
Definition at line 22 of file ConfigReader.java.
ParameterDistributor slogo.frontend.Config.ConfigReader.paramDistributor private
Definition at line 24 of file ConfigReader.java.
Referenced by slogo.frontend.Config.ConfigReader.readFile().
String slogo.frontend.Config.ConfigReader.path = "src/slogo/frontend/Config/Config.txt" private
Definition at line 23 of file ConfigReader.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/frontend/Config/ConfigReader.java