slogo_team03: slogo.UI.SelectorCreator Class Reference
slogo.UI.SelectorCreator Class Reference
Public Member Functions
SelectorCreator (Group root)
Protected Member Functions
void setUpSelector (String prompt, int width, int height, double d, List< String > items)
ComboBox< String > getSelector ()
VBox createSelectorWithLabel (String s, int fontsize, Color color)
Private Attributes
ComboBox< String > mySelector
Group myRoot
Detailed Description
Definition at line 10 of file SelectorCreator.java.
Constructor & Destructor Documentation
slogo.UI.SelectorCreator.SelectorCreator (Group root)
Definition at line 15 of file SelectorCreator.java.
Member Function Documentation
VBox slogo.UI.SelectorCreator.createSelectorWithLabel (String s, int fontsize, Color color) protected
Definition at line 32 of file SelectorCreator.java.
References slogo.UI.LabelCreator.createLabel().
Referenced by slogo.UI.PathTextureSelector.create(), and slogo.UI.TurtleImageSelector.create().
ComboBox<String> slogo.UI.SelectorCreator.getSelector () protected
Definition at line 28 of file SelectorCreator.java.
References slogo.UI.SelectorCreator.mySelector.
Referenced by slogo.UI.PathTextureSelector.create(), and slogo.UI.TurtleImageSelector.create().
void slogo.UI.SelectorCreator.setUpSelector (String prompt, int width, int height, double d, List< String > items) protected
Definition at line 20 of file SelectorCreator.java.
Referenced by slogo.UI.PathTextureSelector.create(), and slogo.UI.TurtleImageSelector.create().
Member Data Documentation
Group slogo.UI.SelectorCreator.myRoot private
Definition at line 13 of file SelectorCreator.java.
ComboBox<String> slogo.UI.SelectorCreator.mySelector private
Definition at line 12 of file SelectorCreator.java.
Referenced by slogo.UI.SelectorCreator.getSelector().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/SelectorCreator.java