slogo_team03: slogo.backend.impl.evaluation.Evaluator Class Reference
slogo.backend.impl.evaluation.Evaluator Class Reference
Public Member Functions
IExecutionContext evaluate (ISyntaxNode current, IExecutionContext previous) throws MalformedSyntaxException
Detailed Description
Definition at line 11 of file Evaluator.java.
Member Function Documentation
IExecutionContext slogo.backend.impl.evaluation.Evaluator.evaluate (ISyntaxNode current, IExecutionContext previous) throws MalformedSyntaxException
Implements slogo.backend.evaluation.IEvaluator.
Definition at line 14 of file Evaluator.java.
References slogo.backend.parsing.ISyntaxNode.children().
Referenced by slogo.backend.impl.Backend.execute(), slogo.backend.impl.evaluation.commands.multipleturtle.Ask.executeRaw(), slogo.backend.impl.evaluation.commands.control.ConditionalOperation.kipling(), and slogo.backend.impl.evaluation.commands.control.LoopOperation.loop().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/evaluation/Evaluator.java