slogo_team03: slogo.backend.impl.tokenization.Tokenizer Class Reference
slogo.backend.impl.tokenization.Tokenizer Class Reference
Public Member Functions
Tokenizer (List< ITokenRule > rules) throws InvalidTokenRulesException
List< IToken > tokenize (Reader input) throws IOException
void loadTokenRules (List< ITokenRule > rules) throws InvalidTokenRulesException
Private Attributes
List< ITokenRule > rules
Detailed Description
Definition at line 15 of file Tokenizer.java.
Constructor & Destructor Documentation
slogo.backend.impl.tokenization.Tokenizer.Tokenizer (List< ITokenRule > rules) throws InvalidTokenRulesException
Definition at line 18 of file Tokenizer.java.
References slogo.backend.impl.tokenization.Tokenizer.loadTokenRules().
Member Function Documentation
void slogo.backend.impl.tokenization.Tokenizer.loadTokenRules (List< ITokenRule > rules) throws InvalidTokenRulesException
Load rules for recognizing tokens
Parameters
rules a list of rules
Exceptions
InvalidTokenRulesException
Implements slogo.backend.tokenization.ITokenizer.
Definition at line 61 of file Tokenizer.java.
References slogo.backend.impl.tokenization.Tokenizer.rules.
Referenced by slogo.backend.impl.tokenization.Tokenizer.Tokenizer().
List<IToken> slogo.backend.impl.tokenization.Tokenizer.tokenize (Reader input) throws IOException
Convert a stream into a list of characters
Parameters
input an input stream of characters
Returns
a list of tokens, in order
Exceptions
IOException
MalformedSyntaxException
Implements slogo.backend.tokenization.ITokenizer.
Definition at line 23 of file Tokenizer.java.
References slogo.Constants.BODY_TOKEN_STRING, slogo.Constants.CLOSING_TOKEN_STRING, and slogo.backend.tokenization.IToken.text().
Referenced by slogo.backend.impl.Backend.execute().
Member Data Documentation
List<ITokenRule> slogo.backend.impl.tokenization.Tokenizer.rules private
Definition at line 16 of file Tokenizer.java.
Referenced by slogo.backend.impl.tokenization.Tokenizer.loadTokenRules().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/tokenization/Tokenizer.java