slogo_team03: slogo.backend.impl.tokenization.TokenRule Class Reference
slogo.backend.impl.tokenization.TokenRule Class Reference
Classes
class Builder
Public Member Functions
String toString ()
Map< String, IToken > match (String text, boolean isStart, boolean isEnd)
Private Member Functions
TokenRule (Builder builder)
Map< String, IToken > matchRaw (String text, List< String > parts)
Pattern generatePattern (List< String > parts)
Private Attributes
final String type
Map< String, String > definition
final boolean ignoreCase
Detailed Description
Definition at line 14 of file TokenRule.java.
Constructor & Destructor Documentation
slogo.backend.impl.tokenization.TokenRule.TokenRule (Builder builder) private
Definition at line 53 of file TokenRule.java.
References slogo.backend.impl.tokenization.TokenRule.Builder.definition, slogo.backend.impl.tokenization.TokenRule.Builder.ignoreCase, and slogo.backend.impl.tokenization.TokenRule.Builder.type.
Referenced by slogo.backend.impl.tokenization.TokenRule.Builder.build().
Member Function Documentation
Pattern slogo.backend.impl.tokenization.TokenRule.generatePattern (List< String > parts) private
Definition at line 77 of file TokenRule.java.
Referenced by slogo.backend.impl.tokenization.TokenRule.matchRaw().
Map<String, IToken> slogo.backend.impl.tokenization.TokenRule.match (String text, boolean isStart, boolean isEnd)
Check if a string of text matches and tokenize it if so
Parameters
text the text to match for
isStart whether the text is at the start of the stream
isEnd whether the text is at the end of the stream
Returns
A map with "opening", "body", and "closing" keys corresponding to the tokens representing the opening, body, and closing
Implements slogo.backend.tokenization.ITokenRule.
Definition at line 88 of file TokenRule.java.
References slogo.Constants.BODY_TOKEN_STRING, slogo.Constants.CLOSING_TOKEN_STRING, slogo.backend.impl.tokenization.TokenRule.matchRaw(), and slogo.Constants.OPENING_TOKEN_STRING.
Referenced by slogo.backend.impl.tokenization.TokenRule.matchRaw().
Map<String, IToken> slogo.backend.impl.tokenization.TokenRule.matchRaw (String text, List< String > parts) private
Definition at line 64 of file TokenRule.java.
References slogo.backend.impl.tokenization.TokenRule.generatePattern(), slogo.backend.impl.tokenization.TokenRule.match(), and slogo.backend.impl.tokenization.TokenRule.type.
Referenced by slogo.backend.impl.tokenization.TokenRule.match().
String slogo.backend.impl.tokenization.TokenRule.toString ()
Definition at line 60 of file TokenRule.java.
References slogo.backend.impl.tokenization.TokenRule.type.
Member Data Documentation
Map<String, String> slogo.backend.impl.tokenization.TokenRule.definition private
Definition at line 16 of file TokenRule.java.
final boolean slogo.backend.impl.tokenization.TokenRule.ignoreCase private
Definition at line 17 of file TokenRule.java.
final String slogo.backend.impl.tokenization.TokenRule.type private
Definition at line 15 of file TokenRule.java.
Referenced by slogo.backend.impl.tokenization.TokenRule.matchRaw(), and slogo.backend.impl.tokenization.TokenRule.toString().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/tokenization/TokenRule.java