slogo_team03: slogo.UI.ToroidalHelper Class Reference
slogo.UI.ToroidalHelper Class Reference
Public Member Functions
ToroidalHelper (List< Line > lineList)
List< Line > makeLinesToroidal ()
Package Attributes
List< Line > lineList
Private Member Functions
void cutLines (Line l, List< Line > lines, double angle)
void runXCalculations (Line l, double angle, List< Line > lines)
void runYShift (List< Line > oldLines, double angle, List< Line > newLines)
void runYCalculations (Line l, double angle, List< Line > lines)
void runLineYShift (Line l)
void runLineXShift (Line l)
void setLineCoords (Line l, double start_x, double start_y, double end_x, double end_y)
boolean checkAllBounds (Line l)
boolean checkEndBounds (Line l)
boolean checkStartBounds (Line l)
boolean checkXBounds (double x)
boolean checkYBounds (double y)
Static Private Attributes
static final Integer MAX_X
static final Integer MIN_X = AppConstants.CANVAS_OFFSET_X_POS
static final Integer MAX_Y
static final Integer MIN_Y = AppConstants.CANVAS_OFFSET_Y_POS
static final Integer WIDTH = AppConstants.CANVAS_WIDTH
static final Integer HEIGHT = AppConstants.CANVAS_HEIGHT
Detailed Description
10/26/2014
Version 1
Author
Michael Deng
Michael Ren
Eric Chen
Nick Widmaier
Definition at line 19 of file ToroidalHelper.java.
Constructor & Destructor Documentation
slogo.UI.ToroidalHelper.ToroidalHelper (List< Line > lineList)
Constructor
Parameters
lineList The list of "un-toroidalled" lines
Definition at line 36 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.lineList.
Member Function Documentation
boolean slogo.UI.ToroidalHelper.checkAllBounds (Line l) private
Checks all the bounds of a line
Parameters
l The current line
Returns
True if the whole line is in the canvas
Definition at line 227 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkEndBounds(), and slogo.UI.ToroidalHelper.checkStartBounds().
boolean slogo.UI.ToroidalHelper.checkEndBounds (Line l) private
Checks if the end coordinate point is in the canvas
Parameters
l The current line
Returns
True if the end point is in the canvas
Definition at line 237 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkXBounds(), and slogo.UI.ToroidalHelper.checkYBounds().
Referenced by slogo.UI.ToroidalHelper.checkAllBounds(), and slogo.UI.ToroidalHelper.makeLinesToroidal().
boolean slogo.UI.ToroidalHelper.checkStartBounds (Line l) private
Checks if the start coordinate point is in the canvas
Parameters
l The current line
Returns
True if the start point is in the canvas
Definition at line 247 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.MIN_Y.
Referenced by slogo.UI.ToroidalHelper.checkAllBounds(), and slogo.UI.ToroidalHelper.cutLines().
boolean slogo.UI.ToroidalHelper.checkXBounds (double x) private
Checks the if the x bounds of a coordinate point fall in the canvas
Parameters
x The x coordinate
Returns
True if the x bound is within the canvas
Definition at line 258 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.checkEndBounds(), slogo.UI.ToroidalHelper.runLineXShift(), and slogo.UI.ToroidalHelper.runXCalculations().
boolean slogo.UI.ToroidalHelper.checkYBounds (double y) private
Checks the if the y bounds of a coordinate point fall in the canvas
Parameters
y The y coordinate
Returns
True if the y bound is within the canvas
Definition at line 268 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.checkEndBounds(), slogo.UI.ToroidalHelper.runLineYShift(), and slogo.UI.ToroidalHelper.runYCalculations().
void slogo.UI.ToroidalHelper.cutLines (Line l, List< Line > lines, double angle) private
Cuts the lines into smaller segments that fit in the canvas
Parameters
l The current un-toroidalled line
lines The new list of lines that will be populated
angle The angle of the original line
Definition at line 76 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkStartBounds(), slogo.UI.ToroidalHelper.runLineXShift(), slogo.UI.ToroidalHelper.runLineYShift(), slogo.UI.ToroidalHelper.runXCalculations(), and slogo.UI.ToroidalHelper.runYShift().
Referenced by slogo.UI.ToroidalHelper.makeLinesToroidal().
List<Line> slogo.UI.ToroidalHelper.makeLinesToroidal ()
Makes the lines toroidal and puts them in a list
Returns
The new list with toroidal lines
Definition at line 45 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkEndBounds(), and slogo.UI.ToroidalHelper.cutLines().
Referenced by slogo.UI.MethodRunner.drawLinesUsingToroidal().
void slogo.UI.ToroidalHelper.runLineXShift (Line l) private
Shifts a lines x position by multiples of the width of the canvas
Parameters
l The current un-toroidalled line
Definition at line 192 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkXBounds(), slogo.UI.ToroidalHelper.MAX_X, slogo.UI.ToroidalHelper.MIN_X, and slogo.UI.ToroidalHelper.WIDTH.
Referenced by slogo.UI.ToroidalHelper.cutLines().
void slogo.UI.ToroidalHelper.runLineYShift (Line l) private
Shifts a lines y position by multiples of the height of the canvas
Parameters
l The current un-toroidalled line
Definition at line 174 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkYBounds(), slogo.UI.ToroidalHelper.HEIGHT, slogo.UI.ToroidalHelper.MAX_Y, and slogo.UI.ToroidalHelper.MIN_Y.
Referenced by slogo.UI.ToroidalHelper.cutLines(), and slogo.UI.ToroidalHelper.runYShift().
void slogo.UI.ToroidalHelper.runXCalculations (Line l, double angle, List< Line > lines) private
Calculates the split of two lines crossing the X boundary
Parameters
l The current un-toroidalled line
angle The angle of the original line
lines The new list of lines that will be populated
Definition at line 94 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkXBounds(), slogo.UI.ToroidalHelper.MAX_X, slogo.UI.ToroidalHelper.MIN_X, slogo.UI.ToroidalHelper.setLineCoords(), and slogo.UI.ToroidalHelper.WIDTH.
Referenced by slogo.UI.ToroidalHelper.cutLines().
void slogo.UI.ToroidalHelper.runYCalculations (Line l, double angle, List< Line > lines) private
Calculates the split of two lines crossing the Y boundary
Parameters
l The current un-toroidalled line
angle The angle of the original line
lines The new list of lines that will be populatedd
Definition at line 143 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.checkYBounds(), slogo.UI.ToroidalHelper.HEIGHT, slogo.UI.ToroidalHelper.MAX_Y, slogo.UI.ToroidalHelper.MIN_Y, and slogo.UI.ToroidalHelper.setLineCoords().
Referenced by slogo.UI.ToroidalHelper.runYShift().
void slogo.UI.ToroidalHelper.runYShift (List< Line > oldLines, double angle, List< Line > newLines) private
Shifts lines that all have the same x positions vertically to fit into one canvas
Parameters
oldLines The old list filled with lines that need to be adjusted
angle The angle of the original line
newLines The new list of lines that will be populated
Definition at line 129 of file ToroidalHelper.java.
References slogo.UI.ToroidalHelper.runLineYShift(), and slogo.UI.ToroidalHelper.runYCalculations().
Referenced by slogo.UI.ToroidalHelper.cutLines().
void slogo.UI.ToroidalHelper.setLineCoords (Line l, double start_x, double start_y, double end_x, double end_y) private
Sets the coordinates of a line
Parameters
l The line
start_x The starting x position of the line
start_y The starting y position of the line
end_x The ending x position of the line
end_y The ending y position of the line
Definition at line 214 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.runXCalculations(), and slogo.UI.ToroidalHelper.runYCalculations().
Member Data Documentation
final Integer slogo.UI.ToroidalHelper.HEIGHT = AppConstants.CANVAS_HEIGHT static private
Definition at line 29 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.runLineYShift(), and slogo.UI.ToroidalHelper.runYCalculations().
List<Line> slogo.UI.ToroidalHelper.lineList package
Definition at line 21 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.ToroidalHelper().
final Integer slogo.UI.ToroidalHelper.MAX_X static private
Initial value:
= AppConstants.CANVAS_WIDTH +
            AppConstants.CANVAS_OFFSET_X_POS
Definition at line 22 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.runLineXShift(), and slogo.UI.ToroidalHelper.runXCalculations().
final Integer slogo.UI.ToroidalHelper.MAX_Y static private
Initial value:
= AppConstants.CANVAS_HEIGHT +
            AppConstants.CANVAS_OFFSET_Y_POS
Definition at line 25 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.runLineYShift(), and slogo.UI.ToroidalHelper.runYCalculations().
final Integer slogo.UI.ToroidalHelper.MIN_X = AppConstants.CANVAS_OFFSET_X_POS static private
Definition at line 24 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.runLineXShift(), and slogo.UI.ToroidalHelper.runXCalculations().
final Integer slogo.UI.ToroidalHelper.MIN_Y = AppConstants.CANVAS_OFFSET_Y_POS static private
Definition at line 27 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.checkStartBounds(), slogo.UI.ToroidalHelper.runLineYShift(), and slogo.UI.ToroidalHelper.runYCalculations().
final Integer slogo.UI.ToroidalHelper.WIDTH = AppConstants.CANVAS_WIDTH static private
Definition at line 28 of file ToroidalHelper.java.
Referenced by slogo.UI.ToroidalHelper.runLineXShift(), and slogo.UI.ToroidalHelper.runXCalculations().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/ToroidalHelper.java