slogo_team03: slogo.backend.impl.util.Qualities Class Reference
slogo.backend.impl.util.Qualities Class Reference
Public Member Functions
Qualities (Color background, Color path, int imageIndex, int thickness)
Color backgroundColor ()
Color toColor ()
int index ()
int thickness ()
void setIndex (int i)
void setBackground (Color c)
Private Attributes
Color backgroundColor
Color pathColor
int myShapeIndex
int myThickness
Detailed Description
Definition at line 5 of file Qualities.java.
Constructor & Destructor Documentation
slogo.backend.impl.util.Qualities.Qualities (Color background, Color path, int imageIndex, int thickness)
Definition at line 12 of file Qualities.java.
References slogo.backend.impl.util.Qualities.thickness().
Member Function Documentation
Color slogo.backend.impl.util.Qualities.backgroundColor ()
Definition at line 19 of file Qualities.java.
int slogo.backend.impl.util.Qualities.index ()
Definition at line 27 of file Qualities.java.
References slogo.backend.impl.util.Qualities.myShapeIndex.
Referenced by slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), and slogo.UI.MethodRunner.setTurtleImage().
void slogo.backend.impl.util.Qualities.setBackground (Color c)
Definition at line 39 of file Qualities.java.
Referenced by slogo.backend.impl.evaluation.commands.multipleturtle.Tell.executeRaw().
void slogo.backend.impl.util.Qualities.setIndex (int i)
Definition at line 35 of file Qualities.java.
Referenced by slogo.UI.MethodRunner.setTurtleImage().
int slogo.backend.impl.util.Qualities.thickness ()
Definition at line 31 of file Qualities.java.
References slogo.backend.impl.util.Qualities.myThickness.
Referenced by slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.util.Qualities.Qualities(), and slogo.UI.MethodRunner.setPenThickness().
Color slogo.backend.impl.util.Qualities.toColor ()
Definition at line 23 of file Qualities.java.
References slogo.backend.impl.util.Qualities.pathColor.
Referenced by slogo.UI.MethodRunner.drawNewLine(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), and slogo.UI.MethodRunner.setPenColor().
Member Data Documentation
Color slogo.backend.impl.util.Qualities.backgroundColor private
Definition at line 7 of file Qualities.java.
Referenced by slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), and slogo.UI.MethodRunner.setBackgroundColor().
int slogo.backend.impl.util.Qualities.myShapeIndex private
Definition at line 9 of file Qualities.java.
Referenced by slogo.backend.impl.util.Qualities.index().
int slogo.backend.impl.util.Qualities.myThickness private
Definition at line 10 of file Qualities.java.
Referenced by slogo.backend.impl.util.Qualities.thickness().
Color slogo.backend.impl.util.Qualities.pathColor private
Definition at line 8 of file Qualities.java.
Referenced by slogo.backend.impl.util.Qualities.toColor().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/util/Qualities.java