slogo_team03: slogo.backend.impl.util.TurtleStatus.Builder Class Reference
slogo.backend.impl.util.TurtleStatus.Builder Class Reference
Public Member Functions
Builder ()
Builder (ITurtleStatus status)
Builder lineSequence (List< ILine > lines)
Builder turtlePosition (ICoordinates position)
Builder turtleDirection (IDirection direction)
Builder penState (PenState state)
Builder turtleVisibility (Visibility visibility)
Builder isActive (boolean isActive)
Builder turtleQualities (Qualities qualities)
TurtleStatus build ()
Private Attributes
List< ILine > lineSequence
ICoordinates turtlePosition
IDirection turtleDirection
PenState penState
Visibility turtleVisibility
boolean isActive
Qualities turtleQualities
Detailed Description
Definition at line 23 of file TurtleStatus.java.
Constructor & Destructor Documentation
slogo.backend.impl.util.TurtleStatus.Builder.Builder ()
Definition at line 32 of file TurtleStatus.java.
References slogo.backend.util.PenState.DOWN, and slogo.backend.util.Visibility.VISIBLE.
slogo.backend.impl.util.TurtleStatus.Builder.Builder (ITurtleStatus status)
Definition at line 42 of file TurtleStatus.java.
References slogo.backend.util.ITurtleStatus.isActive(), slogo.backend.util.ITurtleStatus.lineSequence(), slogo.backend.util.ITurtleStatus.penState(), slogo.backend.util.ITurtleStatus.turtleDirection(), slogo.backend.util.ITurtleStatus.turtlePosition(), slogo.backend.util.ITurtleStatus.turtleQualities(), and slogo.backend.util.ITurtleStatus.turtleVisibility().
Member Function Documentation
TurtleStatus slogo.backend.impl.util.TurtleStatus.Builder.build ()
Definition at line 87 of file TurtleStatus.java.
References slogo.backend.impl.util.TurtleStatus.TurtleStatus().
Referenced by slogo.backend.impl.Backend.Backend(), and slogo.backend.impl.evaluation.commands.multipleturtle.Tell.executeRaw().
Builder slogo.backend.impl.util.TurtleStatus.Builder.isActive (boolean isActive)
Definition at line 77 of file TurtleStatus.java.
References slogo.backend.impl.util.TurtleStatus.Builder.isActive.
Builder slogo.backend.impl.util.TurtleStatus.Builder.lineSequence (List< ILine > lines)
Definition at line 52 of file TurtleStatus.java.
Builder slogo.backend.impl.util.TurtleStatus.Builder.penState (PenState state)
Definition at line 67 of file TurtleStatus.java.
Builder slogo.backend.impl.util.TurtleStatus.Builder.turtleDirection (IDirection direction)
Definition at line 62 of file TurtleStatus.java.
Builder slogo.backend.impl.util.TurtleStatus.Builder.turtlePosition (ICoordinates position)
Definition at line 57 of file TurtleStatus.java.
Builder slogo.backend.impl.util.TurtleStatus.Builder.turtleQualities (Qualities qualities)
Definition at line 82 of file TurtleStatus.java.
Builder slogo.backend.impl.util.TurtleStatus.Builder.turtleVisibility (Visibility visibility)
Definition at line 72 of file TurtleStatus.java.
Member Data Documentation
boolean slogo.backend.impl.util.TurtleStatus.Builder.isActive private
Definition at line 29 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.isActive(), and slogo.backend.impl.util.TurtleStatus.TurtleStatus().
List<ILine> slogo.backend.impl.util.TurtleStatus.Builder.lineSequence private
Definition at line 24 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.TurtleStatus().
PenState slogo.backend.impl.util.TurtleStatus.Builder.penState private
Definition at line 27 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.TurtleStatus().
IDirection slogo.backend.impl.util.TurtleStatus.Builder.turtleDirection private
Definition at line 26 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.TurtleStatus().
ICoordinates slogo.backend.impl.util.TurtleStatus.Builder.turtlePosition private
Definition at line 25 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.TurtleStatus().
Qualities slogo.backend.impl.util.TurtleStatus.Builder.turtleQualities private
Definition at line 30 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.TurtleStatus().
Visibility slogo.backend.impl.util.TurtleStatus.Builder.turtleVisibility private
Definition at line 28 of file TurtleStatus.java.
Referenced by slogo.backend.impl.util.TurtleStatus.TurtleStatus().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/util/TurtleStatus.java