slogo_team03: slogo.backend.impl.tokenization.TokenRule.Builder Class Reference
slogo.backend.impl.tokenization.TokenRule.Builder Class Reference
Public Member Functions
Builder (String type, String body)
Builder opening (String opening)
Builder closing (String closing)
Builder ignoreCase (boolean ignoreCase)
TokenRule build ()
Private Attributes
final String type
Map< String, String > definition
boolean ignoreCase
Detailed Description
Definition at line 19 of file TokenRule.java.
Constructor & Destructor Documentation
slogo.backend.impl.tokenization.TokenRule.Builder.Builder (String type, String body)
Definition at line 24 of file TokenRule.java.
References slogo.Constants.BODY_TOKEN_STRING, slogo.Constants.CLOSING_TOKEN_STRING, slogo.Constants.OPENING_TOKEN_STRING, and slogo.backend.impl.tokenization.TokenRule.Builder.type.
Member Function Documentation
TokenRule slogo.backend.impl.tokenization.TokenRule.Builder.build ()
Definition at line 48 of file TokenRule.java.
References slogo.backend.impl.tokenization.TokenRule.TokenRule().
Referenced by slogo.backend.test.TokenizationTest.testMatch(), slogo.backend.test.TokenizationTest.testTokenize(), and slogo.backend.impl.Backend.tokenRules().
Builder slogo.backend.impl.tokenization.TokenRule.Builder.closing (String closing)
Definition at line 38 of file TokenRule.java.
References slogo.Constants.CLOSING_TOKEN_STRING.
Builder slogo.backend.impl.tokenization.TokenRule.Builder.ignoreCase (boolean ignoreCase)
Definition at line 43 of file TokenRule.java.
References slogo.backend.impl.tokenization.TokenRule.Builder.ignoreCase.
Builder slogo.backend.impl.tokenization.TokenRule.Builder.opening (String opening)
Definition at line 33 of file TokenRule.java.
References slogo.Constants.OPENING_TOKEN_STRING.
Member Data Documentation
Map<String, String> slogo.backend.impl.tokenization.TokenRule.Builder.definition private
Definition at line 21 of file TokenRule.java.
Referenced by slogo.backend.impl.tokenization.TokenRule.TokenRule().
boolean slogo.backend.impl.tokenization.TokenRule.Builder.ignoreCase private
Definition at line 22 of file TokenRule.java.
Referenced by slogo.backend.impl.tokenization.TokenRule.Builder.ignoreCase(), and slogo.backend.impl.tokenization.TokenRule.TokenRule().
final String slogo.backend.impl.tokenization.TokenRule.Builder.type private
Definition at line 20 of file TokenRule.java.
Referenced by slogo.backend.impl.tokenization.TokenRule.Builder.Builder(), and slogo.backend.impl.tokenization.TokenRule.TokenRule().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/tokenization/TokenRule.java