slogo_team03: slogo.UI.ModuleCreationHelper Class Reference
slogo.UI.ModuleCreationHelper Class Reference
Public Member Functions
ModuleCreationHelper (Group root, Scene scene, Stage stage)
void createMainPageModules ()
void activateExitAppButton (Button btn)
void activatePlayButton (Button btn)
void activatePauseButton (Button btn)
void activateResetButton (Button btn)
void activateHelpButton (Button btn)
void activateDebugCB (CheckBox cb)
void activateLoadButton (Button btn)
void activateSaveButton (Button btn)
void activateExtraWorkspaceButton (Button btn)
void activateStepIntoButton (Button btn)
void activateStepOverButton (Button btn)
void activateTextField (TextField TF)
void stepThroughCommandsHistory (int offset)
void setCommandsHistoryCounter (int value)
int getCommandsHistoryCounter ()
void resetCommandsHistoryList (int oldCounter)
List< Turtle > getActiveTurtles ()
Canvas getCanvas ()
void setView (View view)
double getAnimationSliderValue ()
void turnOnRunningStatusLabel ()
void turnOffRunningStatusLabel ()
List< Turtle > getTurtleList ()
void clearUserVariables ()
Protected Member Functions
void setListViewVariables (double x, double y, double o, boolean b, int t)
TurtleImageSelector getTurtleSelector ()
PathColorSelector getPathColorSelector ()
BackgroundColorSelector getBackgroundColorSelector ()
void setUserVariable (String environment)
Private Member Functions
void createSelectorVBoxModules ()
void createFirstRowButtons ()
void createSecondRowButtons ()
void createDebugModules ()
void createListScrollPane ()
void createModuleScrollPane ()
void createGridCheckBox ()
void createFirstButtonRow ()
void createSecondButtonRow ()
void createTitle ()
void createTurtleCanvas ()
void createTurtle ()
void createPlayButton ()
void createStopButton ()
void createPauseButton ()
void createResetButton ()
void createHelpButton ()
void createTurtleImageLoaderButton ()
void createIncreaseDecreaseButtons ()
void createNewTurtleButton ()
void createLoadButton ()
void createSaveButton ()
void createExtraWorkspaceButton ()
void createAnimationSpeedSlider ()
void createDebugButton ()
void createDebugVBox ()
void createDebugLabel ()
void createDebugStepIntoButton ()
void createDebugStepOverButton ()
void createRunningStatusLabel ()
void createTextField ()
void createLabelsCheckBox ()
void createListViews ()
void createSelectorVBox ()
void createListVBox ()
void createSelectors ()
void activateTurtleCanvas ()
void activateNewTurtleButton (Button btn)
void activateTurtleImageLoaderButton (Button btn)
void activateCheckBoxCreator (CheckBox cb)
void activateIncreaseDecreaseButtons (Button incbtn, Button decbtn, View view)
void activateKeyEvents ()
void addToCertainList (ObservableList< String > currentList, ListViewAllSLOGO listView, String input)
void clearCertainList (ObservableList< String > currentList, ListViewAllSLOGO listView)
Private Attributes
ConfigReader configReader
ConfigWriter configWriter
Stage stage
View myView
Group root
Scene scene
HBox firstButtonRow
HBox secondButtonRow
TurtleCanvas myCanvas
CommandsTextField myTextField
List< Turtle > myTurtleList
VBox mySelectorsVBox
VBox myListsVBox
ListViewPreviousCommands myCommandsList
ListViewSLOGOVariables myVariablesList
ListViewUserVariables myUserVariablesList
ListViewUserCommands myUserCommandsList
ObservableList< String > myCommands = FXCollections.observableArrayList()
ObservableList< String > myVariables = FXCollections.observableArrayList()
ObservableList< String > myUserVariables = FXCollections.observableArrayList()
ObservableList< String > myUserCommands = FXCollections.observableArrayList()
GraphicsContext myGraphicsContext
Slider animationSlider
ScrollPane moduleScrollPane
ScrollPane listScrollPane
Map< String, Node > myImagesMap
int totalUserImages
TurtleImageSelector myTurtleSelector
List< Line > myGridLines
int totalTurtles
VBox debugVBox
Label debugLabel
Button debugStepIntoButton
Button debugStepOverButton
Boolean isInDebugMode
Label runningStatusLabel
int commandsHistoryCounter
PathColorSelector myPathColorSelector
BackgroundColorSelector myBackgroundColorSelector
CheckBox labelsCheckBox
Detailed Description
October 8th, 2014
Version 1
Author
Nick Widmaier
Michael Deng
Michael Ren
Eric Chen
Definition at line 51 of file ModuleCreationHelper.java.
Constructor & Destructor Documentation
slogo.UI.ModuleCreationHelper.ModuleCreationHelper (Group root, Scene scene, Stage stage)
The constructor
Parameters
root The group all the modules are placed in
Definition at line 103 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.root, slogo.UI.ModuleCreationHelper.scene, and slogo.UI.ModuleCreationHelper.stage.
Member Function Documentation
void slogo.UI.ModuleCreationHelper.activateCheckBoxCreator (CheckBox cb) private
Activates an event handler that creates labels for the turtles when fired
Parameters
cb The checkbox that fires the event
Definition at line 819 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.createLabelsCheckBox().
void slogo.UI.ModuleCreationHelper.activateDebugCB (CheckBox cb)
Creates an event handler that shows and hides the debug modules when fired
Parameters
cb The checkbox that fires the event
Definition at line 633 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.createDebugButton().
void slogo.UI.ModuleCreationHelper.activateExitAppButton (Button btn)
Creates an event handler than exits the application on button click.
Parameters
btn : The button that is clicked to launch the event.
Definition at line 556 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.createStopButton().
void slogo.UI.ModuleCreationHelper.activateExtraWorkspaceButton (Button btn)
Creates an event handler that creates a new window when fired
Parameters
btn The button that fires the event
Definition at line 720 of file ModuleCreationHelper.java.
References slogo.UI.Main.start().
Referenced by slogo.UI.ModuleCreationHelper.createExtraWorkspaceButton().
void slogo.UI.ModuleCreationHelper.activateHelpButton (Button btn)
Lets the help button navigate to a help website
Parameters
btn The help button
Definition at line 618 of file ModuleCreationHelper.java.
References slogo.UI.HTMLHelpPage.displayPage(), and slogo.UI.AppConstants.HELP_URL.
Referenced by slogo.UI.ModuleCreationHelper.createHelpButton().
void slogo.UI.ModuleCreationHelper.activateIncreaseDecreaseButtons (Button incbtn, Button decbtn, View view) private
Creates an event handler that increases or decreases stroke width based on what button is pressed
Parameters
incbtn The button that increases width
decbtn The button that decreases width
view The view
Definition at line 847 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.getActiveTurtles(), slogo.UI.Turtle.getThickness(), slogo.View.sendCommandToBackend(), and slogo.UI.Turtle.setThickness().
Referenced by slogo.UI.ModuleCreationHelper.createIncreaseDecreaseButtons().
void slogo.UI.ModuleCreationHelper.activateKeyEvents () private
Activates key events that move the turtle when fired
Definition at line 869 of file ModuleCreationHelper.java.
References slogo.View.sendCommandToBackend().
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.activateLoadButton (Button btn)
Lets the load button load a configuration file
Parameters
btn The load button
Definition at line 658 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.addToCertainList(), slogo.UI.ModuleCreationHelper.clearCertainList(), slogo.frontend.Config.ParameterDistributor.getColorMap(), slogo.frontend.Config.ParameterDistributor.getNumOfTurtles(), slogo.frontend.Config.ParameterDistributor.getVariableMap(), and slogo.frontend.Config.ConfigReader.readFile().
Referenced by slogo.UI.ModuleCreationHelper.createLoadButton().
void slogo.UI.ModuleCreationHelper.activateNewTurtleButton (Button btn) private
Creates an event handler that generates a new turtle when fired
Parameters
btn The button that fires the event
Definition at line 782 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.getActiveTurtles(), and slogo.View.sendCommandToBackend().
Referenced by slogo.UI.ModuleCreationHelper.createNewTurtleButton().
void slogo.UI.ModuleCreationHelper.activatePauseButton (Button btn)
Creates an event handler that pauses animation when fired
Parameters
btn The button the fires the event
Definition at line 589 of file ModuleCreationHelper.java.
References slogo.View.pauseAnimation().
Referenced by slogo.UI.ModuleCreationHelper.createPauseButton().
void slogo.UI.ModuleCreationHelper.activatePlayButton (Button btn)
Creates an event handler that plays the animation whenever the event is fired
Parameters
btn The button that fires the event
Definition at line 570 of file ModuleCreationHelper.java.
References slogo.View.sendCommandToBackend().
Referenced by slogo.UI.ModuleCreationHelper.createPlayButton().
void slogo.UI.ModuleCreationHelper.activateResetButton (Button btn)
Creates an event handler that resets the animation when fired
Parameters
btn The button the fires the event
Definition at line 603 of file ModuleCreationHelper.java.
References slogo.View.resetAnimation().
Referenced by slogo.UI.ModuleCreationHelper.createResetButton().
void slogo.UI.ModuleCreationHelper.activateSaveButton (Button btn)
Lets the save button save to a configuration file
Parameters
btn The save button
Definition at line 691 of file ModuleCreationHelper.java.
References slogo.frontend.Config.ConfigHashMapCreator.getConfigHashMap(), slogo.UI.ListViewAllSLOGO.getItems(), slogo.frontend.Config.ConfigHashMapCreator.setNumOfTurtles(), slogo.frontend.Config.ConfigHashMapCreator.setVariableMap(), and slogo.frontend.Config.ConfigWriter.writeToTextFile().
Referenced by slogo.UI.ModuleCreationHelper.createSaveButton().
void slogo.UI.ModuleCreationHelper.activateStepIntoButton (Button btn)
Creates an event handler that steps through commands when fired
Parameters
btn The button that fires the event
Definition at line 736 of file ModuleCreationHelper.java.
References slogo.View.stepIntoCommand(), and slogo.UI.ModuleCreationHelper.stepThroughCommandsHistory().
Referenced by slogo.UI.ModuleCreationHelper.createDebugStepIntoButton().
void slogo.UI.ModuleCreationHelper.activateStepOverButton (Button btn)
Creates an event handler that steps over commands when fired
Parameters
btn The button that fires the event
Definition at line 751 of file ModuleCreationHelper.java.
References slogo.View.stepOverCommand(), and slogo.UI.ModuleCreationHelper.stepThroughCommandsHistory().
Referenced by slogo.UI.ModuleCreationHelper.createDebugStepOverButton().
void slogo.UI.ModuleCreationHelper.activateTextField (TextField TF)
Creates an event handler that records the text in the text box when fired
Parameters
TF The text field that fires the event
Definition at line 766 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.addToCertainList(), slogo.UI.CommandsTextField.getText(), slogo.View.recordCommand(), and slogo.UI.CommandsTextField.setText().
Referenced by slogo.UI.ModuleCreationHelper.createTextField().
void slogo.UI.ModuleCreationHelper.activateTurtleCanvas () private
Creates the turtle canvas
Definition at line 536 of file ModuleCreationHelper.java.
References slogo.UI.TurtleCanvas.getCanvas(), slogo.UI.ListViewAllSLOGO.getItems(), slogo.UI.AppConstants.INITIAL_TURTLE_X_POS, slogo.UI.AppConstants.INITIAL_TURTLE_Y_POS, and slogo.View.sendCommandToBackend().
Referenced by slogo.UI.ModuleCreationHelper.createTurtleCanvas().
void slogo.UI.ModuleCreationHelper.activateTurtleImageLoaderButton (Button btn) private
Activates an event handler that opens up a file directory when fired
Parameters
btn The button that fires the event
Definition at line 803 of file ModuleCreationHelper.java.
References slogo.UI.ImageLoader.chooseNewImage().
Referenced by slogo.UI.ModuleCreationHelper.createTurtleImageLoaderButton().
void slogo.UI.ModuleCreationHelper.addToCertainList (ObservableList< String > currentList, ListViewAllSLOGO listView, String input) private
Adds values to a list
Parameters
currentList The observable list
listView The physical list interface
input The values that needs to be added to the list
Definition at line 896 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.setItems().
Referenced by slogo.UI.ModuleCreationHelper.activateLoadButton(), slogo.UI.ModuleCreationHelper.activateTextField(), and slogo.UI.ModuleCreationHelper.createListViews().
void slogo.UI.ModuleCreationHelper.clearCertainList (ObservableList< String > currentList, ListViewAllSLOGO listView) private
Clears all values from a list
Parameters
currentList The observable list
listView The physical list interface
Definition at line 909 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.setItems().
Referenced by slogo.UI.ModuleCreationHelper.activateLoadButton().
void slogo.UI.ModuleCreationHelper.clearUserVariables ()
Clears the UserVariables List - needed so UI does not have duplicates of variables
Definition at line 1089 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.getItems().
Referenced by slogo.View.executeCommand().
void slogo.UI.ModuleCreationHelper.createAnimationSpeedSlider () private
Creates a slider that controls animation speed
Definition at line 394 of file ModuleCreationHelper.java.
References slogo.UI.AppConstants.ANIMATION_SLIDER_DEFAULT_VALUE, slogo.UI.AppConstants.ANIMATION_SLIDER_MAX_VALUE, slogo.UI.AppConstants.ANIMATION_SLIDER_MIN_VALUE, slogo.UI.LabelCreator.createLabel(), slogo.UI.SliderCreator.createSlider(), slogo.UI.AppConstants.DEFAULT_TEXT_COLOR, and slogo.UI.AppConstants.LABEL_FONT_SIZE.
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createDebugButton () private
Creates a button that activates and deactivates debug mode
Definition at line 408 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateDebugCB(), and slogo.UI.CheckBoxCreator.createCheckBox().
Referenced by slogo.UI.ModuleCreationHelper.createDebugModules().
void slogo.UI.ModuleCreationHelper.createDebugLabel () private
Creates the label that indicates debug mode
Definition at line 427 of file ModuleCreationHelper.java.
References slogo.UI.LabelCreator.createLabel(), and slogo.UI.AppConstants.DEBUG_LABEL_FONT_SIZE.
Referenced by slogo.UI.ModuleCreationHelper.createDebugModules().
void slogo.UI.ModuleCreationHelper.createDebugModules () private
Creates all the debugging modules
Definition at line 175 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.createDebugButton(), slogo.UI.ModuleCreationHelper.createDebugLabel(), slogo.UI.ModuleCreationHelper.createDebugStepIntoButton(), slogo.UI.ModuleCreationHelper.createDebugStepOverButton(), and slogo.UI.ModuleCreationHelper.createDebugVBox().
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createDebugStepIntoButton () private
Creates a button that steps through commands
Definition at line 436 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateStepIntoButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createDebugModules().
void slogo.UI.ModuleCreationHelper.createDebugStepOverButton () private
Creates a button that steps over commands
Definition at line 446 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateStepOverButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createDebugModules().
void slogo.UI.ModuleCreationHelper.createDebugVBox () private
Creates a VBox that holds all debug modules
Definition at line 417 of file ModuleCreationHelper.java.
References slogo.UI.VBoxCreator.createVBox(), slogo.UI.AppConstants.DEBUG_LABEL_X_POS, slogo.UI.AppConstants.DEBUG_LABEL_Y_POS, and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createDebugModules().
void slogo.UI.ModuleCreationHelper.createExtraWorkspaceButton () private
Creates an extra workspace window
Definition at line 385 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateExtraWorkspaceButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createFirstButtonRow () private
Creates a HBox for the buttons
Definition at line 218 of file ModuleCreationHelper.java.
References slogo.UI.HBoxCreator.createHBox(), and slogo.UI.AppConstants.STAGE_PADDING.
Referenced by slogo.UI.ModuleCreationHelper.createFirstRowButtons().
void slogo.UI.ModuleCreationHelper.createFirstRowButtons () private
Creates the first row of buttons
Definition at line 157 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.createFirstButtonRow(), slogo.UI.ModuleCreationHelper.createPlayButton(), and slogo.UI.ModuleCreationHelper.createStopButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createGridCheckBox () private
Creates a checkBox for the Grid
Definition at line 210 of file ModuleCreationHelper.java.
References slogo.UI.GridLinesToggler.activate().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createHelpButton () private
Creates the help link button
Definition at line 328 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateHelpButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createIncreaseDecreaseButtons () private
Creates the buttons that increase and decrease stroke width
Definition at line 346 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateIncreaseDecreaseButtons(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createLabelsCheckBox () private
Creates the label checkbox for activating the turtles' labels
Definition at line 476 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateCheckBoxCreator(), and slogo.UI.CheckBoxCreator.createCheckBox().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createListScrollPane () private
Creates a Scroll Pane for the lists in the application
Definition at line 186 of file ModuleCreationHelper.java.
References slogo.UI.ScrollPaneCreator.createScrollPane(), slogo.UI.AppConstants.LIST_SCROLL_PANE_HEIGHT, slogo.UI.AppConstants.LIST_SCROLL_PANE_WIDTH, slogo.UI.AppConstants.LIST_SCROLL_PANE_X_POS, and slogo.UI.AppConstants.LIST_SCROLL_PANE_Y_POS.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createListVBox () private
Creates a vBox that stores all the lists
Definition at line 509 of file ModuleCreationHelper.java.
References slogo.UI.VBoxCreator.createVBoxScrollable(), and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createListViews () private
Creates all the lists for each of the variables and commans
Definition at line 485 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.addToCertainList(), slogo.UI.ListViewUserCommands.create(), slogo.UI.ListViewPreviousCommands.create(), slogo.UI.ListViewUserVariables.create(), and slogo.UI.ListViewSLOGOVariables.create().
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createLoadButton () private
Creates a button that loads in a config file
Definition at line 367 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateLoadButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createMainPageModules ()
Populates the scene with modules
Definition at line 119 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateKeyEvents(), slogo.UI.ModuleCreationHelper.createDebugModules(), slogo.UI.ModuleCreationHelper.createListScrollPane(), slogo.UI.ModuleCreationHelper.createListVBox(), slogo.UI.ModuleCreationHelper.createListViews(), slogo.UI.ModuleCreationHelper.createModuleScrollPane(), slogo.UI.ModuleCreationHelper.createRunningStatusLabel(), slogo.UI.ModuleCreationHelper.createSelectorVBox(), slogo.UI.ModuleCreationHelper.createSelectorVBoxModules(), slogo.UI.ModuleCreationHelper.createTitle(), slogo.UI.ModuleCreationHelper.createTurtle(), and slogo.UI.ModuleCreationHelper.createTurtleCanvas().
Referenced by slogo.UI.Main.start().
void slogo.UI.ModuleCreationHelper.createModuleScrollPane () private
Creates a Scroll Pane for the modules in the application
Definition at line 198 of file ModuleCreationHelper.java.
References slogo.UI.ScrollPaneCreator.createScrollPane(), slogo.UI.AppConstants.FIRST_SCROLL_PANE_HEIGHT, slogo.UI.AppConstants.FIRST_SCROLL_PANE_WIDTH, slogo.UI.AppConstants.FIRST_SCROLL_PANE_X_POS, and slogo.UI.AppConstants.FIRST_SCROLL_PANE_Y_POS.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createNewTurtleButton () private
Add another turtle to scene
Definition at line 358 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateNewTurtleButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createPauseButton () private
Creates a button that pauses animation
Definition at line 299 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activatePauseButton(), slogo.UI.ButtonCreator.createButton(), slogo.UI.LabelCreator.createLabel(), slogo.UI.VBoxCreator.createVBox(), slogo.UI.AppConstants.DEFAULT_TEXT_COLOR, slogo.UI.AppConstants.LABEL_FONT_SIZE, and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createSecondRowButtons().
void slogo.UI.ModuleCreationHelper.createPlayButton () private
Creates a button that runs animations
Definition at line 267 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activatePlayButton(), slogo.UI.ButtonCreator.createButton(), slogo.UI.LabelCreator.createLabel(), slogo.UI.VBoxCreator.createVBox(), slogo.UI.AppConstants.DEFAULT_TEXT_COLOR, slogo.UI.AppConstants.LABEL_FONT_SIZE, and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createFirstRowButtons().
void slogo.UI.ModuleCreationHelper.createResetButton () private
Creates a button that resets animation
Definition at line 314 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateResetButton(), slogo.UI.ButtonCreator.createButton(), slogo.UI.LabelCreator.createLabel(), slogo.UI.VBoxCreator.createVBox(), slogo.UI.AppConstants.DEFAULT_TEXT_COLOR, slogo.UI.AppConstants.LABEL_FONT_SIZE, and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createSecondRowButtons().
void slogo.UI.ModuleCreationHelper.createRunningStatusLabel () private
Creates a label that displays whenever an animation is running
Definition at line 456 of file ModuleCreationHelper.java.
References slogo.UI.LabelCreator.createLabel(), slogo.UI.AppConstants.RUNNING_STATUS_LABEL_X_POS, slogo.UI.AppConstants.RUNNING_STATUS_LABEL_Y_POS, and slogo.UI.AppConstants.TITLE_LABEL_FONT_SIZE.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createSaveButton () private
Create a button that saves to a config file
Definition at line 376 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateSaveButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createSecondButtonRow () private
Creates a HBox for buttons below the first row of buttons
Definition at line 226 of file ModuleCreationHelper.java.
References slogo.UI.HBoxCreator.createHBox(), and slogo.UI.AppConstants.STAGE_PADDING.
Referenced by slogo.UI.ModuleCreationHelper.createSecondRowButtons().
void slogo.UI.ModuleCreationHelper.createSecondRowButtons () private
Creates the second row of buttons
Definition at line 166 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.createPauseButton(), slogo.UI.ModuleCreationHelper.createResetButton(), and slogo.UI.ModuleCreationHelper.createSecondButtonRow().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createSelectors () private
Creates all of the selectors for the application
Definition at line 518 of file ModuleCreationHelper.java.
References slogo.UI.PathColorSelector.create(), slogo.UI.PathTextureSelector.create(), slogo.UI.BackgroundColorSelector.create(), slogo.UI.TurtleImageSelector.create(), and slogo.UI.ModuleCreationHelper.myView.
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createSelectorVBox () private
Creates a VBox for all of the selectors
Definition at line 500 of file ModuleCreationHelper.java.
References slogo.UI.VBoxCreator.createVBoxScrollable(), and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createSelectorVBoxModules () private
Creates the modules in the first scrolling pane
Definition at line 137 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.createAnimationSpeedSlider(), slogo.UI.ModuleCreationHelper.createExtraWorkspaceButton(), slogo.UI.ModuleCreationHelper.createFirstRowButtons(), slogo.UI.ModuleCreationHelper.createGridCheckBox(), slogo.UI.ModuleCreationHelper.createHelpButton(), slogo.UI.ModuleCreationHelper.createIncreaseDecreaseButtons(), slogo.UI.ModuleCreationHelper.createLabelsCheckBox(), slogo.UI.ModuleCreationHelper.createLoadButton(), slogo.UI.ModuleCreationHelper.createNewTurtleButton(), slogo.UI.ModuleCreationHelper.createSaveButton(), slogo.UI.ModuleCreationHelper.createSecondRowButtons(), slogo.UI.ModuleCreationHelper.createSelectors(), slogo.UI.ModuleCreationHelper.createTextField(), and slogo.UI.ModuleCreationHelper.createTurtleImageLoaderButton().
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createStopButton () private
Creates the button that exits the application
Definition at line 283 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateExitAppButton(), slogo.UI.ButtonCreator.createButton(), slogo.UI.LabelCreator.createLabel(), slogo.UI.VBoxCreator.createVBox(), slogo.UI.AppConstants.DEFAULT_TEXT_COLOR, slogo.UI.AppConstants.LABEL_FONT_SIZE, and slogo.UI.AppConstants.VBOX_SPACING.
Referenced by slogo.UI.ModuleCreationHelper.createFirstRowButtons().
void slogo.UI.ModuleCreationHelper.createTextField () private
Creates the text field where the user enters code
Definition at line 468 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateTextField(), slogo.UI.CommandsTextField.createTextField(), and slogo.UI.CommandsTextField.getTextField().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
void slogo.UI.ModuleCreationHelper.createTitle () private
Creates the title for our application
Definition at line 234 of file ModuleCreationHelper.java.
References slogo.UI.LabelCreator.createLabel(), slogo.UI.AppConstants.TITLE_LABEL_FONT_SIZE, slogo.UI.AppConstants.TITLE_X_POS, and slogo.UI.AppConstants.TITLE_Y_POS.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createTurtle () private
Creates the turtle object on the canvas
Definition at line 252 of file ModuleCreationHelper.java.
References slogo.UI.AppConstants.INITIAL_TURTLE_X_POS, and slogo.UI.AppConstants.INITIAL_TURTLE_Y_POS.
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createTurtleCanvas () private
Creates the canvas on which the turtle runs
Definition at line 243 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateTurtleCanvas(), and slogo.UI.TurtleCanvas.getGraphicsContext().
Referenced by slogo.UI.ModuleCreationHelper.createMainPageModules().
void slogo.UI.ModuleCreationHelper.createTurtleImageLoaderButton () private
Creates a button that loads an image for the turtle
Definition at line 337 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.activateTurtleImageLoaderButton(), and slogo.UI.ButtonCreator.createButton().
Referenced by slogo.UI.ModuleCreationHelper.createSelectorVBoxModules().
List<Turtle> slogo.UI.ModuleCreationHelper.getActiveTurtles ()
Returns the current active turtle
Returns
The turtle
Definition at line 970 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.activateIncreaseDecreaseButtons(), and slogo.UI.ModuleCreationHelper.activateNewTurtleButton().
double slogo.UI.ModuleCreationHelper.getAnimationSliderValue ()
Gets the value of of the animation slider
Returns
The slider value
Definition at line 1003 of file ModuleCreationHelper.java.
Referenced by slogo.View.sendCommandToBackend().
BackgroundColorSelector slogo.UI.ModuleCreationHelper.getBackgroundColorSelector () protected
Gets the background color selector
Returns
The background color selector
Definition at line 1063 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.myBackgroundColorSelector.
Referenced by slogo.UI.MethodRunner.setBackgroundColor().
Canvas slogo.UI.ModuleCreationHelper.getCanvas ()
Returns the canvas
Returns
The canvas
Definition at line 985 of file ModuleCreationHelper.java.
References slogo.UI.TurtleCanvas.getCanvas().
Referenced by slogo.View.initRunner(), and slogo.UI.MethodRunner.setBackgroundColor().
int slogo.UI.ModuleCreationHelper.getCommandsHistoryCounter ()
Gets the value of the command history counter
Returns
The command history counter
Definition at line 943 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.commandsHistoryCounter.
Referenced by slogo.View.sendCommandToBackend().
PathColorSelector slogo.UI.ModuleCreationHelper.getPathColorSelector () protected
Gets the line color selector
Returns
The color selector for the lines
Definition at line 1054 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.myPathColorSelector.
Referenced by slogo.UI.MethodRunner.setPenColor().
List<Turtle> slogo.UI.ModuleCreationHelper.getTurtleList ()
Gets the list of turtles
Returns
The list of turtles
Definition at line 1072 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.myTurtleList.
Referenced by slogo.UI.MethodRunner.changeTurtle(), and slogo.View.initRunner().
TurtleImageSelector slogo.UI.ModuleCreationHelper.getTurtleSelector () protected
Gets the turtles image
Returns
The turtle's image
Definition at line 1045 of file ModuleCreationHelper.java.
References slogo.UI.ModuleCreationHelper.myTurtleSelector.
Referenced by slogo.UI.MethodRunner.setTurtleImage().
void slogo.UI.ModuleCreationHelper.resetCommandsHistoryList (int oldCounter)
Resets the command history counter to an old state
Parameters
oldCounter The old state of the command history counter
Definition at line 952 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.setItems().
Referenced by slogo.View.resetAnimation().
void slogo.UI.ModuleCreationHelper.setCommandsHistoryCounter (int value)
Sets the value of the command history counter
Parameters
value The value
Definition at line 934 of file ModuleCreationHelper.java.
Referenced by slogo.View.resetAnimation().
void slogo.UI.ModuleCreationHelper.setListViewVariables (double x, double y, double o, boolean b, int t) protected
Sets the values of the variables in the list
Parameters
x The turtle's x position
y The turtle's y position
o The orientation of the turtle
b The boolean representing the pen down or pen up
t The thickness of the pen
Definition at line 1016 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.setItems().
Referenced by slogo.UI.MethodRunner.changeTurtle().
void slogo.UI.ModuleCreationHelper.setUserVariable (String environment) protected
Used for adding variables the user dedines to the display
Parameters
environment the string representing the variables
Definition at line 1081 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.getItems().
Referenced by slogo.UI.MethodRunner.changeEnvironment().
void slogo.UI.ModuleCreationHelper.setView (View view)
Sets the value of myView
Parameters
view The view
Definition at line 994 of file ModuleCreationHelper.java.
Referenced by slogo.UI.Main.start().
void slogo.UI.ModuleCreationHelper.stepThroughCommandsHistory (int offset)
Steps through or over commands, depending on the offset
Parameters
offset The offset of stepping
Definition at line 919 of file ModuleCreationHelper.java.
References slogo.UI.ListViewAllSLOGO.setItems().
Referenced by slogo.UI.ModuleCreationHelper.activateStepIntoButton(), slogo.UI.ModuleCreationHelper.activateStepOverButton(), and slogo.View.sendCommandToBackend().
void slogo.UI.ModuleCreationHelper.turnOffRunningStatusLabel ()
Makes the running status label invisible
Definition at line 1036 of file ModuleCreationHelper.java.
Referenced by slogo.View.pauseAnimation(), slogo.View.resetAnimation(), and slogo.View.sendCommandToBackend().
void slogo.UI.ModuleCreationHelper.turnOnRunningStatusLabel ()
Makes the running status label visible
Definition at line 1029 of file ModuleCreationHelper.java.
Referenced by slogo.View.sendCommandToBackend().
Member Data Documentation
Slider slogo.UI.ModuleCreationHelper.animationSlider private
Definition at line 75 of file ModuleCreationHelper.java.
int slogo.UI.ModuleCreationHelper.commandsHistoryCounter private
Definition at line 93 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.getCommandsHistoryCounter().
ConfigReader slogo.UI.ModuleCreationHelper.configReader private
Definition at line 53 of file ModuleCreationHelper.java.
ConfigWriter slogo.UI.ModuleCreationHelper.configWriter private
Definition at line 54 of file ModuleCreationHelper.java.
Label slogo.UI.ModuleCreationHelper.debugLabel private
Definition at line 87 of file ModuleCreationHelper.java.
Button slogo.UI.ModuleCreationHelper.debugStepIntoButton private
Definition at line 88 of file ModuleCreationHelper.java.
Button slogo.UI.ModuleCreationHelper.debugStepOverButton private
Definition at line 89 of file ModuleCreationHelper.java.
VBox slogo.UI.ModuleCreationHelper.debugVBox private
Definition at line 86 of file ModuleCreationHelper.java.
HBox slogo.UI.ModuleCreationHelper.firstButtonRow private
Definition at line 59 of file ModuleCreationHelper.java.
Boolean slogo.UI.ModuleCreationHelper.isInDebugMode private
Definition at line 90 of file ModuleCreationHelper.java.
CheckBox slogo.UI.ModuleCreationHelper.labelsCheckBox private
Definition at line 96 of file ModuleCreationHelper.java.
ScrollPane slogo.UI.ModuleCreationHelper.listScrollPane private
Definition at line 77 of file ModuleCreationHelper.java.
ScrollPane slogo.UI.ModuleCreationHelper.moduleScrollPane private
Definition at line 76 of file ModuleCreationHelper.java.
BackgroundColorSelector slogo.UI.ModuleCreationHelper.myBackgroundColorSelector private
Definition at line 95 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.getBackgroundColorSelector().
TurtleCanvas slogo.UI.ModuleCreationHelper.myCanvas private
Definition at line 61 of file ModuleCreationHelper.java.
ObservableList<String> slogo.UI.ModuleCreationHelper.myCommands = FXCollections.observableArrayList() private
Definition at line 70 of file ModuleCreationHelper.java.
ListViewPreviousCommands slogo.UI.ModuleCreationHelper.myCommandsList private
Definition at line 66 of file ModuleCreationHelper.java.
GraphicsContext slogo.UI.ModuleCreationHelper.myGraphicsContext private
Definition at line 74 of file ModuleCreationHelper.java.
List<Line> slogo.UI.ModuleCreationHelper.myGridLines private
Definition at line 83 of file ModuleCreationHelper.java.
Map<String, Node> slogo.UI.ModuleCreationHelper.myImagesMap private
Definition at line 79 of file ModuleCreationHelper.java.
VBox slogo.UI.ModuleCreationHelper.myListsVBox private
Definition at line 65 of file ModuleCreationHelper.java.
PathColorSelector slogo.UI.ModuleCreationHelper.myPathColorSelector private
Definition at line 94 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.getPathColorSelector().
VBox slogo.UI.ModuleCreationHelper.mySelectorsVBox private
Definition at line 64 of file ModuleCreationHelper.java.
CommandsTextField slogo.UI.ModuleCreationHelper.myTextField private
Definition at line 62 of file ModuleCreationHelper.java.
List<Turtle> slogo.UI.ModuleCreationHelper.myTurtleList private
Definition at line 63 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.getTurtleList().
TurtleImageSelector slogo.UI.ModuleCreationHelper.myTurtleSelector private
Definition at line 81 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.getTurtleSelector().
ObservableList<String> slogo.UI.ModuleCreationHelper.myUserCommands = FXCollections.observableArrayList() private
Definition at line 73 of file ModuleCreationHelper.java.
ListViewUserCommands slogo.UI.ModuleCreationHelper.myUserCommandsList private
Definition at line 69 of file ModuleCreationHelper.java.
ObservableList<String> slogo.UI.ModuleCreationHelper.myUserVariables = FXCollections.observableArrayList() private
Definition at line 72 of file ModuleCreationHelper.java.
ListViewUserVariables slogo.UI.ModuleCreationHelper.myUserVariablesList private
Definition at line 68 of file ModuleCreationHelper.java.
ObservableList<String> slogo.UI.ModuleCreationHelper.myVariables = FXCollections.observableArrayList() private
Definition at line 71 of file ModuleCreationHelper.java.
ListViewSLOGOVariables slogo.UI.ModuleCreationHelper.myVariablesList private
Definition at line 67 of file ModuleCreationHelper.java.
View slogo.UI.ModuleCreationHelper.myView private
Definition at line 56 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.createSelectors().
Group slogo.UI.ModuleCreationHelper.root private
Definition at line 57 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.ModuleCreationHelper().
Label slogo.UI.ModuleCreationHelper.runningStatusLabel private
Definition at line 92 of file ModuleCreationHelper.java.
Scene slogo.UI.ModuleCreationHelper.scene private
Definition at line 58 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.ModuleCreationHelper().
HBox slogo.UI.ModuleCreationHelper.secondButtonRow private
Definition at line 60 of file ModuleCreationHelper.java.
Stage slogo.UI.ModuleCreationHelper.stage private
Definition at line 55 of file ModuleCreationHelper.java.
Referenced by slogo.UI.ModuleCreationHelper.ModuleCreationHelper().
int slogo.UI.ModuleCreationHelper.totalTurtles private
Definition at line 84 of file ModuleCreationHelper.java.
int slogo.UI.ModuleCreationHelper.totalUserImages private
Definition at line 80 of file ModuleCreationHelper.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/ModuleCreationHelper.java