slogo_team03: slogo.View Class Reference
slogo.View Class Reference
Public Member Functions
void init (Group root, ModuleCreationHelper MCH)
void initRunner (Group root, ModuleCreationHelper MCH)
void recordCommand (String command)
void sendCommandToBackend ()
void resetAnimation ()
void pauseAnimation ()
void sendCommandToBackend (String command)
void stepIntoCommand ()
void stepOverCommand ()
void init ()
Private Member Functions
void executeTurtleCommands (String k, ITurtleStatus iTurtleStatus)
void executeEnvironmentCommands (String var)
void executeCommand (IExecutionContext result)
Private Attributes
MethodRunner runner
IModel backend
List< Line > pathList
Queue< String > commandQueue
Queue< String > immediateHistoryQueue
int recordCommandHistoryCounter
Timeline animationTimeline
ModuleCreationHelper MCH
Detailed Description
This class connects our user interface to the back end Our modulecreationhelper sets a view which allows the user controls to send commands to the back end when they are clicked on the view then sends these to the backend, which processes them and returns them for the method runner to use to update all the user interface commands
Author
Michael Deng
Nick Widmaier
Michael Ren
Eric Chen
Definition at line 54 of file View.java.
Member Function Documentation
void slogo.View.executeCommand (IExecutionContext result) private
goes through the returns from the backend and executes the commands for each turtle, as well as the environment
Parameters
result the context returned by the backend
Definition at line 266 of file View.java.
References slogo.UI.ModuleCreationHelper.clearUserVariables(), slogo.backend.evaluation.IExecutionContext.environment(), slogo.View.executeEnvironmentCommands(), slogo.View.executeTurtleCommands(), and slogo.backend.evaluation.IExecutionContext.turtles().
Referenced by slogo.View.sendCommandToBackend(), slogo.View.stepIntoCommand(), and slogo.View.stepOverCommand().
void slogo.View.executeEnvironmentCommands (String var) private
Executes the command based off the status returned from backend to update the variables
Parameters
var string representing variables
Definition at line 256 of file View.java.
References slogo.UI.MethodRunner.changeEnvironment(), and slogo.UI.MethodRunner.setEnvironment().
Referenced by slogo.View.executeCommand().
void slogo.View.executeTurtleCommands (String k, ITurtleStatus iTurtleStatus) private
Executes the command based off status returned from the backend
Parameters
str
iTurtleStatus the status of the turtle from the backend
Definition at line 245 of file View.java.
References slogo.UI.MethodRunner.changeTurtle(), and slogo.UI.MethodRunner.setTurtleStatus().
Referenced by slogo.View.executeCommand().
void slogo.View.init (Group root, ModuleCreationHelper MCH)
Initializes the View
Parameters
root The Group all the modules are placed on
canvas The canvas on which the turtle is drawn
turtle The moving object on the canvas
Definition at line 72 of file View.java.
References slogo.View.MCH.
Referenced by slogo.UI.Main.start().
void slogo.View.init ()
Start up the UI
Implements slogo.IView.
Definition at line 277 of file View.java.
void slogo.View.initRunner (Group root, ModuleCreationHelper MCH)
initialize the runner so that it can use update all the modules correctly
Parameters
root the root we add UI elements to
MCH the class that creates all the modules
Definition at line 89 of file View.java.
References slogo.UI.ModuleCreationHelper.getCanvas(), slogo.UI.ModuleCreationHelper.getTurtleList(), slogo.View.MCH, and slogo.View.pathList.
Referenced by slogo.UI.Main.start().
void slogo.View.pauseAnimation ()
pauses the animation while in the middle of running through commands can be resumed to run through the rest of the commands
Definition at line 178 of file View.java.
References slogo.UI.ModuleCreationHelper.turnOffRunningStatusLabel().
Referenced by slogo.UI.ModuleCreationHelper.activatePauseButton().
void slogo.View.recordCommand (String command)
Stores the command in the queue
Parameters
command The input from the user
Definition at line 97 of file View.java.
Referenced by slogo.UI.ModuleCreationHelper.activateTextField().
void slogo.View.resetAnimation ()
resets the animation, stopping it from playing commands list is reset and user would have to enter more commands to run it
Definition at line 154 of file View.java.
References slogo.UI.ModuleCreationHelper.resetCommandsHistoryList(), slogo.UI.ModuleCreationHelper.setCommandsHistoryCounter(), and slogo.UI.ModuleCreationHelper.turnOffRunningStatusLabel().
Referenced by slogo.UI.ModuleCreationHelper.activateResetButton().
void slogo.View.sendCommandToBackend ()
sends the string to the backend for evaluation will do so based on the animation timeline - if active, it will evaluate the command and then display the animation
Definition at line 107 of file View.java.
References slogo.IModel.execute(), slogo.View.executeCommand(), slogo.UI.ModuleCreationHelper.getAnimationSliderValue(), slogo.UI.ModuleCreationHelper.getCommandsHistoryCounter(), slogo.UI.ModuleCreationHelper.stepThroughCommandsHistory(), slogo.UI.ModuleCreationHelper.turnOffRunningStatusLabel(), and slogo.UI.ModuleCreationHelper.turnOnRunningStatusLabel().
Referenced by slogo.UI.ModuleCreationHelper.activateIncreaseDecreaseButtons(), slogo.UI.ModuleCreationHelper.activateKeyEvents(), slogo.UI.ModuleCreationHelper.activateNewTurtleButton(), slogo.UI.ModuleCreationHelper.activatePlayButton(), slogo.UI.ModuleCreationHelper.activateTurtleCanvas(), slogo.UI.PathColorSelector.create(), slogo.UI.BackgroundColorSelector.create(), and slogo.UI.TurtleImageSelector.create().
void slogo.View.sendCommandToBackend (String command)
Sends a command to the back-end
Parameters
command The code written by the user to be computed
Definition at line 190 of file View.java.
References slogo.IModel.execute(), and slogo.View.executeCommand().
void slogo.View.stepIntoCommand ()
steps into a command for debugging easy to go through one command at a time
Definition at line 204 of file View.java.
References slogo.IModel.execute(), and slogo.View.executeCommand().
Referenced by slogo.UI.ModuleCreationHelper.activateStepIntoButton().
void slogo.View.stepOverCommand ()
steps over a particular command, also for debugging
Definition at line 223 of file View.java.
References slogo.IModel.execute(), and slogo.View.executeCommand().
Referenced by slogo.UI.ModuleCreationHelper.activateStepOverButton().
Member Data Documentation
Timeline slogo.View.animationTimeline private
Definition at line 62 of file View.java.
IModel slogo.View.backend private
Definition at line 57 of file View.java.
Queue<String> slogo.View.commandQueue private
Definition at line 59 of file View.java.
Queue<String> slogo.View.immediateHistoryQueue private
Definition at line 60 of file View.java.
ModuleCreationHelper slogo.View.MCH private
Definition at line 63 of file View.java.
Referenced by slogo.View.init(), and slogo.View.initRunner().
List<Line> slogo.View.pathList private
Definition at line 58 of file View.java.
Referenced by slogo.View.initRunner().
int slogo.View.recordCommandHistoryCounter private
Definition at line 61 of file View.java.
MethodRunner slogo.View.runner private
Definition at line 56 of file View.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/View.java