slogo_team03: slogo.UI.SliderCreator Class Reference
slogo.UI.SliderCreator Class Reference
Public Member Functions
SliderCreator (VBox vBox)
Slider createSlider (int minValue, int maxValue, int currentValue)
Slider createSlider (int minValue, int maxValue, int currentValue, int x_Coord, int y_Coord)
Private Attributes
VBox vBox
Detailed Description
Definition at line 7 of file SliderCreator.java.
Constructor & Destructor Documentation
slogo.UI.SliderCreator.SliderCreator (VBox vBox)
Definition at line 11 of file SliderCreator.java.
References slogo.UI.SliderCreator.vBox.
Member Function Documentation
Slider slogo.UI.SliderCreator.createSlider (int minValue, int maxValue, int currentValue)
Method to create the slider for animation speed
Parameters
minValue Smallest value of slider
maxValue Largest value of slider
currentValue The default value of the slider
Returns
The slider
Definition at line 23 of file SliderCreator.java.
References slogo.UI.AppConstants.ANIMATION_SLIDER_WIDTH.
Referenced by slogo.UI.ModuleCreationHelper.createAnimationSpeedSlider(), and slogo.UI.SliderCreator.createSlider().
Slider slogo.UI.SliderCreator.createSlider (int minValue, int maxValue, int currentValue, int x_Coord, int y_Coord)
Method to create the slider for animation speed
Parameters
minValue Smallest value of slider
maxValue Largest value of slider
x_Coord X position of slider
y_Coord Y position of slider
currentValue The default value of the slider
Returns
The slider
Definition at line 45 of file SliderCreator.java.
References slogo.UI.SliderCreator.createSlider().
Member Data Documentation
VBox slogo.UI.SliderCreator.vBox private
Definition at line 9 of file SliderCreator.java.
Referenced by slogo.UI.SliderCreator.SliderCreator().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/SliderCreator.java