slogo_team03: slogo.UI.LabelCreator Class Reference
slogo.UI.LabelCreator Class Reference
Public Member Functions
LabelCreator (Group root)
LabelCreator (VBox vBox)
Label createLabel (String content, int fontSize, Color color)
Label createLabel (String content, int xPos, int yPos, int fontSize, Color color)
Private Attributes
Group root
VBox vBox
Detailed Description
Definition at line 9 of file LabelCreator.java.
Constructor & Destructor Documentation
slogo.UI.LabelCreator.LabelCreator (Group root)
Definition at line 14 of file LabelCreator.java.
References slogo.UI.LabelCreator.root.
slogo.UI.LabelCreator.LabelCreator (VBox vBox)
Definition at line 18 of file LabelCreator.java.
References slogo.UI.LabelCreator.vBox.
Member Function Documentation
Label slogo.UI.LabelCreator.createLabel (String content, int fontSize, Color color)
Definition at line 22 of file LabelCreator.java.
Referenced by slogo.UI.ModuleCreationHelper.createAnimationSpeedSlider(), slogo.UI.ModuleCreationHelper.createDebugLabel(), slogo.UI.ListViewCreator.createListViewWithLabel(), slogo.UI.ModuleCreationHelper.createPauseButton(), slogo.UI.ModuleCreationHelper.createPlayButton(), slogo.UI.ModuleCreationHelper.createResetButton(), slogo.UI.ModuleCreationHelper.createRunningStatusLabel(), slogo.UI.ColorSelectorCreator.createSelectorWithLabel(), slogo.UI.SelectorCreator.createSelectorWithLabel(), slogo.UI.ModuleCreationHelper.createStopButton(), slogo.UI.CommandsTextField.createTextField(), and slogo.UI.ModuleCreationHelper.createTitle().
Label slogo.UI.LabelCreator.createLabel (String content, int xPos, int yPos, int fontSize, Color color)
Definition at line 36 of file LabelCreator.java.
Member Data Documentation
Group slogo.UI.LabelCreator.root private
Definition at line 11 of file LabelCreator.java.
Referenced by slogo.UI.LabelCreator.LabelCreator().
VBox slogo.UI.LabelCreator.vBox private
Definition at line 12 of file LabelCreator.java.
Referenced by slogo.UI.LabelCreator.LabelCreator().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/LabelCreator.java