slogo_team03: slogo.backend.impl.evaluation.commands.turtle.PenUp Class Reference
slogo.backend.impl.evaluation.commands.turtle.PenUp Class Reference
Public Member Functions
PenUp ()
Public Member Functions inherited from slogo.backend.impl.evaluation.commands.Operation
Operation (String type, int argMin, int argMax)
IExecutionContext execute (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
String type ()
Protected Member Functions
IExecutionContext executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current)
Protected Member Functions inherited from slogo.backend.impl.evaluation.commands.Operation
void validateArguments (List< IExecutionContext > args) throws MalformedSyntaxException
abstract IExecutionContext executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
List< Number > generateNumericArguments (List< IExecutionContext > args)
IExecutionContext mergeContexts (List< IExecutionContext > contexts)
String getContextReturnValue (IExecutionContext context)
String getContextReturnedVariableName (IExecutionContext context)
Static Private Attributes
static final String COMMAND_NAME = "PenUp"
static final int MIN_NUM_CONTEXT = 1
static final int MAX_NUM_CONTEXT = 1
Detailed Description
Definition at line 17 of file PenUp.java.
Constructor & Destructor Documentation
slogo.backend.impl.evaluation.commands.turtle.PenUp.PenUp ()
Definition at line 22 of file PenUp.java.
Member Function Documentation
IExecutionContext slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) protected
Definition at line 27 of file PenUp.java.
References slogo.Constants.FALSE_STRING, slogo.backend.util.ITurtleStatus.isActive(), slogo.backend.util.ITurtleStatus.lineSequence(), slogo.Constants.RETURN_VALUE_ENVIRONMENT, slogo.backend.util.ITurtleStatus.turtleDirection(), slogo.backend.util.ITurtleStatus.turtlePosition(), slogo.backend.util.ITurtleStatus.turtleQualities(), slogo.backend.evaluation.IExecutionContext.turtles(), slogo.backend.util.ITurtleStatus.turtleVisibility(), and slogo.backend.util.PenState.UP.
Member Data Documentation
final String slogo.backend.impl.evaluation.commands.turtle.PenUp.COMMAND_NAME = "PenUp" static private
Definition at line 18 of file PenUp.java.
final int slogo.backend.impl.evaluation.commands.turtle.PenUp.MAX_NUM_CONTEXT = 1 static private
Definition at line 20 of file PenUp.java.
final int slogo.backend.impl.evaluation.commands.turtle.PenUp.MIN_NUM_CONTEXT = 1 static private
Definition at line 19 of file PenUp.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/evaluation/commands/turtle/PenUp.java