slogo_team03: slogo.UI.BackgroundColorSelector Class Reference
slogo.UI.BackgroundColorSelector Class Reference
Public Member Functions
BackgroundColorSelector (VBox vbox)
void setValue (Color backgroundColor)
Color getValue ()
Protected Member Functions
void create (Group root, GraphicsContext GC, View view)
Private Attributes
VBox myVbox
ColorPicker bgColor
Detailed Description
10/15/2014
Version 1
Author
Michael Deng
Definition at line 21 of file BackgroundColorSelector.java.
Constructor & Destructor Documentation
slogo.UI.BackgroundColorSelector.BackgroundColorSelector (VBox vbox)
Definition at line 25 of file BackgroundColorSelector.java.
Member Function Documentation
void slogo.UI.BackgroundColorSelector.create (Group root, GraphicsContext GC, View view) protected
Definition at line 29 of file BackgroundColorSelector.java.
References slogo.UI.ColorSelectorCreator.createSelectorWithLabel(), slogo.UI.ColorSelectorCreator.getSelector(), slogo.UI.AppConstants.SELECTOR_FONT_SIZE, slogo.UI.AppConstants.SELECTOR_HEIGHT, slogo.UI.AppConstants.SELECTOR_WIDTH, slogo.View.sendCommandToBackend(), slogo.UI.ColorSelectorCreator.setUpSelector(), and slogo.UI.AppConstants.TITLE_LABEL_FONT_SIZE.
Referenced by slogo.UI.ModuleCreationHelper.createSelectors().
Color slogo.UI.BackgroundColorSelector.getValue ()
Definition at line 57 of file BackgroundColorSelector.java.
Referenced by slogo.UI.MethodRunner.setBackgroundColor().
void slogo.UI.BackgroundColorSelector.setValue (Color backgroundColor)
Definition at line 52 of file BackgroundColorSelector.java.
Referenced by slogo.UI.MethodRunner.setBackgroundColor().
Member Data Documentation
ColorPicker slogo.UI.BackgroundColorSelector.bgColor private
Definition at line 23 of file BackgroundColorSelector.java.
VBox slogo.UI.BackgroundColorSelector.myVbox private
Definition at line 22 of file BackgroundColorSelector.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/BackgroundColorSelector.java