slogo_team03: slogo.UI.TurtleCanvas Class Reference
slogo.UI.TurtleCanvas Class Reference
Public Member Functions
TurtleCanvas (Group root)
Protected Member Functions
GraphicsContext getGraphicsContext ()
Canvas getCanvas ()
Private Attributes
Group myRoot
GraphicsContext myGraphicsContext
Canvas myCanvas
Detailed Description
10/10/2014
Version 1
Author
Michael Deng
Definition at line 17 of file TurtleCanvas.java.
Constructor & Destructor Documentation
slogo.UI.TurtleCanvas.TurtleCanvas (Group root)
The constructor
Parameters
root The group the turtle canvas belongs to
Definition at line 28 of file TurtleCanvas.java.
References slogo.UI.AppConstants.CANVAS_HEIGHT, slogo.UI.AppConstants.CANVAS_OFFSET_X_POS, slogo.UI.AppConstants.CANVAS_OFFSET_Y_POS, and slogo.UI.AppConstants.CANVAS_WIDTH.
Member Function Documentation
Canvas slogo.UI.TurtleCanvas.getCanvas () protected
Gets the canvas
Returns
The canvas
Definition at line 56 of file TurtleCanvas.java.
References slogo.UI.TurtleCanvas.myCanvas.
Referenced by slogo.UI.GridLinesToggler.activate(), slogo.UI.ModuleCreationHelper.activateTurtleCanvas(), and slogo.UI.ModuleCreationHelper.getCanvas().
GraphicsContext slogo.UI.TurtleCanvas.getGraphicsContext () protected
Gets the graphics context
Returns
The graphics context
Definition at line 47 of file TurtleCanvas.java.
References slogo.UI.TurtleCanvas.myGraphicsContext.
Referenced by slogo.UI.ModuleCreationHelper.createTurtleCanvas().
Member Data Documentation
Canvas slogo.UI.TurtleCanvas.myCanvas private
Definition at line 21 of file TurtleCanvas.java.
Referenced by slogo.UI.TurtleCanvas.getCanvas().
GraphicsContext slogo.UI.TurtleCanvas.myGraphicsContext private
Definition at line 20 of file TurtleCanvas.java.
Referenced by slogo.UI.TurtleCanvas.getGraphicsContext().
Group slogo.UI.TurtleCanvas.myRoot private
Definition at line 19 of file TurtleCanvas.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/TurtleCanvas.java