slogo_team03: slogo.backend.parsing.ISyntaxNode Interface Reference
slogo.backend.parsing.ISyntaxNode Interface Reference
Public Member Functions
IOperation operation ()
List< ISyntaxNode > children ()
void setChildren (List< ISyntaxNode > children)
String type ()
Detailed Description
A node of an abstract syntax tree
Definition at line 11 of file ISyntaxNode.java.
Member Function Documentation
List<ISyntaxNode> slogo.backend.parsing.ISyntaxNode.children ()
Get the children of this node
Returns
the node's children
Implemented in slogo.backend.impl.parsing.SyntaxNode.
Referenced by slogo.backend.impl.evaluation.Evaluator.evaluate(), and slogo.backend.test.EvaluationTest.setupTree().
IOperation slogo.backend.parsing.ISyntaxNode.operation ()
Get the operation associated with the node
Returns
the operation associated with the node
Implemented in slogo.backend.impl.parsing.SyntaxNode.
void slogo.backend.parsing.ISyntaxNode.setChildren (List< ISyntaxNode > children)
Implemented in slogo.backend.impl.parsing.SyntaxNode.
Referenced by slogo.backend.impl.parsing.Parser.createNestedNode().
String slogo.backend.parsing.ISyntaxNode.type ()
Get a name representing the child
Returns
the name
Implemented in slogo.backend.impl.parsing.SyntaxNode.
Referenced by slogo.backend.test.ParsingTest.testParse().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/parsing/ISyntaxNode.java