slogo_team03: slogo.backend.impl.evaluation.ExecutionContext Class Reference
slogo.backend.impl.evaluation.ExecutionContext Class Reference
Public Member Functions
ExecutionContext (IExecutionContext context)
ExecutionContext (Map< String, ITurtleStatus > myTurtleInfo, Map< String, String > myEnvironmentInfo, Map< String, ISyntaxNode > userDefinedCommands)
Map< String, ITurtleStatus > turtles ()
Map< String, String > environment ()
Map< String, ISyntaxNode > userDefinedCommands ()
Private Attributes
Map< String, ITurtleStatus > turtleInfo
Map< String, String > environmentInfo
Map< String, ISyntaxNode > userDefinedCommands
Detailed Description
The implementation of a context representing the state of execution of a command at a certain point
Definition at line 18 of file ExecutionContext.java.
Constructor & Destructor Documentation
slogo.backend.impl.evaluation.ExecutionContext.ExecutionContext (IExecutionContext context)
Create a deep copy of a previous ExecutionContext
Parameters
context
Definition at line 27 of file ExecutionContext.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.backend.evaluation.IExecutionContext.turtles(), and slogo.backend.evaluation.IExecutionContext.userDefinedCommands().
slogo.backend.impl.evaluation.ExecutionContext.ExecutionContext (Map< String, ITurtleStatus > myTurtleInfo, Map< String, String > myEnvironmentInfo, Map< String, ISyntaxNode > userDefinedCommands)
Create a new execution context from component parts
Parameters
myTurtleInfo The map of turtles to their status
myEnvironmentInfo The environment variables, potentially including the return value
userDefinedCommands The user-defined commands
Definition at line 40 of file ExecutionContext.java.
References slogo.backend.impl.evaluation.ExecutionContext.userDefinedCommands().
Member Function Documentation
Map<String, String> slogo.backend.impl.evaluation.ExecutionContext.environment ()
A general place to put configuration variables, akin to a shell's environment. This can be used to store a return value, for example.
Returns
a key-value Map that represents the list of configuration variables
Implements slogo.backend.evaluation.IExecutionContext.
Definition at line 53 of file ExecutionContext.java.
References slogo.backend.impl.evaluation.ExecutionContext.environmentInfo.
Map<String, ITurtleStatus> slogo.backend.impl.evaluation.ExecutionContext.turtles ()
Get the turtles on the map
Returns
a map of turtle names to turtle status
Implements slogo.backend.evaluation.IExecutionContext.
Definition at line 48 of file ExecutionContext.java.
References slogo.backend.impl.evaluation.ExecutionContext.turtleInfo.
Map<String, ISyntaxNode> slogo.backend.impl.evaluation.ExecutionContext.userDefinedCommands ()
A place for commands that the user defines; the commands are stored in the tree representation created in parsing
Returns
The list of user-defined commands
Implements slogo.backend.evaluation.IExecutionContext.
Definition at line 58 of file ExecutionContext.java.
Referenced by slogo.backend.impl.evaluation.ExecutionContext.ExecutionContext().
Member Data Documentation
Map<String, String> slogo.backend.impl.evaluation.ExecutionContext.environmentInfo private
Definition at line 20 of file ExecutionContext.java.
Referenced by slogo.backend.impl.evaluation.ExecutionContext.environment().
Map<String, ITurtleStatus> slogo.backend.impl.evaluation.ExecutionContext.turtleInfo private
Definition at line 19 of file ExecutionContext.java.
Referenced by slogo.backend.impl.evaluation.ExecutionContext.turtles().
Map<String, ISyntaxNode> slogo.backend.impl.evaluation.ExecutionContext.userDefinedCommands private
Definition at line 21 of file ExecutionContext.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/evaluation/ExecutionContext.java