slogo_team03: slogo.backend.impl.tokenization.Token Class Reference
slogo.backend.impl.tokenization.Token Class Reference
Public Member Functions
Token (String text, String type)
String text ()
String type ()
String toString ()
Private Attributes
String text
String type
Detailed Description
Definition at line 5 of file Token.java.
Constructor & Destructor Documentation
slogo.backend.impl.tokenization.Token.Token (String text, String type)
Definition at line 10 of file Token.java.
References slogo.backend.impl.tokenization.Token.text(), and slogo.backend.impl.tokenization.Token.type().
Member Function Documentation
String slogo.backend.impl.tokenization.Token.text ()
Get the text associated with the token
Returns
the text of the token
Implements slogo.backend.tokenization.IToken.
Definition at line 15 of file Token.java.
Referenced by slogo.backend.impl.tokenization.Token.Token(), and slogo.backend.impl.tokenization.Token.toString().
String slogo.backend.impl.tokenization.Token.toString ()
Definition at line 24 of file Token.java.
References slogo.backend.impl.tokenization.Token.text().
String slogo.backend.impl.tokenization.Token.type ()
Get the type of token
Returns
the type
Implements slogo.backend.tokenization.IToken.
Definition at line 20 of file Token.java.
Referenced by slogo.backend.impl.tokenization.Token.Token().
Member Data Documentation
String slogo.backend.impl.tokenization.Token.text private
Definition at line 7 of file Token.java.
String slogo.backend.impl.tokenization.Token.type private
Definition at line 8 of file Token.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/tokenization/Token.java