slogo_team03: slogo.UI.PathColorSelector Class Reference
slogo.UI.PathColorSelector Class Reference
Public Member Functions
PathColorSelector (VBox vbox)
void setValue (Color color)
Color getValue ()
Protected Member Functions
void create (Group root, Turtle t, View view)
Private Attributes
VBox myVbox
ColorPicker pathColor
Detailed Description
Definition at line 12 of file PathColorSelector.java.
Constructor & Destructor Documentation
slogo.UI.PathColorSelector.PathColorSelector (VBox vbox)
Definition at line 17 of file PathColorSelector.java.
Member Function Documentation
void slogo.UI.PathColorSelector.create (Group root, Turtle t, View view) protected
Definition at line 21 of file PathColorSelector.java.
References slogo.UI.ColorSelectorCreator.createSelectorWithLabel(), slogo.UI.ColorSelectorCreator.getSelector(), slogo.UI.AppConstants.SELECTOR_FONT_SIZE, slogo.UI.AppConstants.SELECTOR_HEIGHT, slogo.UI.AppConstants.SELECTOR_WIDTH, slogo.View.sendCommandToBackend(), slogo.UI.ColorSelectorCreator.setUpSelector(), and slogo.UI.AppConstants.TITLE_LABEL_FONT_SIZE.
Referenced by slogo.UI.ModuleCreationHelper.createSelectors().
Color slogo.UI.PathColorSelector.getValue ()
Definition at line 48 of file PathColorSelector.java.
Referenced by slogo.UI.MethodRunner.setPenColor().
void slogo.UI.PathColorSelector.setValue (Color color)
Definition at line 43 of file PathColorSelector.java.
Referenced by slogo.UI.MethodRunner.setPenColor().
Member Data Documentation
VBox slogo.UI.PathColorSelector.myVbox private
Definition at line 14 of file PathColorSelector.java.
ColorPicker slogo.UI.PathColorSelector.pathColor private
Definition at line 15 of file PathColorSelector.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/PathColorSelector.java