slogo_team03: slogo.backend.impl.evaluation.commands.MathOperation Class Reference
slogo.backend.impl.evaluation.commands.MathOperation Class Reference abstract
Public Member Functions
MathOperation (String type, int argMin, int argMax)
Public Member Functions inherited from slogo.backend.impl.evaluation.commands.Operation
Operation (String type, int argMin, int argMax)
IExecutionContext execute (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
String type ()
Protected Member Functions
IExecutionContext executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
abstract Number executeMath (List< Number > args) throws MalformedSyntaxException
Protected Member Functions inherited from slogo.backend.impl.evaluation.commands.Operation
void validateArguments (List< IExecutionContext > args) throws MalformedSyntaxException
abstract IExecutionContext executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException
List< Number > generateNumericArguments (List< IExecutionContext > args)
IExecutionContext mergeContexts (List< IExecutionContext > contexts)
String getContextReturnValue (IExecutionContext context)
String getContextReturnedVariableName (IExecutionContext context)
Detailed Description
Super class for all math and boolean operations
Definition at line 16 of file MathOperation.java.
Constructor & Destructor Documentation
slogo.backend.impl.evaluation.commands.MathOperation.MathOperation (String type, int argMin, int argMax)
Definition at line 18 of file MathOperation.java.
Member Function Documentation
abstract Number slogo.backend.impl.evaluation.commands.MathOperation.executeMath (List< Number > args) throws MalformedSyntaxException abstract protected
Mathematically evaluate the operation given a list of number arguments
Parameters
args The arguments to pass in for calculation
Returns
The number result
Exceptions
MalformedSyntaxException If there was a problem evaluating the list of numbers, e.g. divide by zero
Referenced by slogo.backend.impl.evaluation.commands.MathOperation.executeRaw().
IExecutionContext slogo.backend.impl.evaluation.commands.MathOperation.executeRaw (List< IExecutionContext > args, IExecutionContext previous, ISyntaxNode current) throws MalformedSyntaxException protected
Take care of packaging the numeric result of executing a math command into an IExecutionContext
Definition at line 27 of file MathOperation.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.backend.impl.evaluation.commands.MathOperation.executeMath(), slogo.backend.impl.evaluation.commands.Operation.generateNumericArguments(), slogo.backend.impl.evaluation.commands.Operation.mergeContexts(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/evaluation/commands/MathOperation.java