slogo_team03: slogo.backend.util.IDirection Interface Reference
slogo.backend.util.IDirection Interface Reference
Public Member Functions
double toDegrees ()
double toRadians ()
Detailed Description
The direction an object faces, with up being 0 degrees
Definition at line 7 of file IDirection.java.
Member Function Documentation
double slogo.backend.util.IDirection.toDegrees ()
Get the direction in degrees
Returns
the direction in degrees
Implemented in slogo.backend.impl.util.Direction.
Referenced by slogo.UI.MethodRunner.changeTurtle(), slogo.backend.impl.evaluation.commands.turtle.Heading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.UI.MethodRunner.setTurtleDirection(), and slogo.backend.test.OperationTest.testForward().
double slogo.backend.util.IDirection.toRadians ()
Get the direction in radians
Returns
the direction in radians
Implemented in slogo.backend.impl.util.Direction.
Referenced by slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), and slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/util/IDirection.java