slogo_team03: slogo.backend.test.BackendTest Class Reference
slogo.backend.test.BackendTest Class Reference
Public Member Functions
void init () throws InitializationException
void testExecute () throws ExecutionException
void testExecuteNegative () throws Exception
void testMake () throws Exception
void testRepeat () throws Exception
void testDoTimes () throws Exception
void testFor () throws Exception
void testIf () throws Exception
void testIfElse () throws Exception
void testTo () throws Exception
void testTell () throws Exception
void testAsk () throws Exception
void testID () throws Exception
void testTurtles () throws Exception
void testLanguages () throws Exception
Private Attributes
IModel backend
Detailed Description
Definition at line 20 of file BackendTest.java.
Member Function Documentation
void slogo.backend.test.BackendTest.init () throws InitializationException
Definition at line 24 of file BackendTest.java.
void slogo.backend.test.BackendTest.testAsk () throws Exception
Definition at line 113 of file BackendTest.java.
References slogo.IModel.execute(), and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.BackendTest.testDoTimes () throws Exception
Definition at line 60 of file BackendTest.java.
References slogo.Constants.DEFAULT_TURTLE_NAME, slogo.IModel.execute(), and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.BackendTest.testExecute () throws ExecutionException
Definition at line 29 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
void slogo.backend.test.BackendTest.testExecuteNegative () throws Exception
Definition at line 40 of file BackendTest.java.
References slogo.IModel.execute().
void slogo.backend.test.BackendTest.testFor () throws Exception
Definition at line 67 of file BackendTest.java.
References slogo.Constants.DEFAULT_TURTLE_NAME, slogo.IModel.execute(), and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.BackendTest.testID () throws Exception
Definition at line 134 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
void slogo.backend.test.BackendTest.testIf () throws Exception
Definition at line 74 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
void slogo.backend.test.BackendTest.testIfElse () throws Exception
Definition at line 80 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
void slogo.backend.test.BackendTest.testLanguages () throws Exception
Definition at line 162 of file BackendTest.java.
References slogo.backend.impl.Languages.buildMap(), and slogo.backend.impl.Languages.returnMap().
void slogo.backend.test.BackendTest.testMake () throws Exception
Definition at line 45 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
void slogo.backend.test.BackendTest.testRepeat () throws Exception
Definition at line 53 of file BackendTest.java.
References slogo.Constants.DEFAULT_TURTLE_NAME, slogo.IModel.execute(), and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.BackendTest.testTell () throws Exception
Definition at line 93 of file BackendTest.java.
References slogo.IModel.execute(), and slogo.backend.evaluation.IExecutionContext.turtles().
void slogo.backend.test.BackendTest.testTo () throws Exception
Definition at line 86 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
void slogo.backend.test.BackendTest.testTurtles () throws Exception
Definition at line 150 of file BackendTest.java.
References slogo.backend.evaluation.IExecutionContext.environment(), slogo.IModel.execute(), and slogo.Constants.RETURN_VALUE_ENVIRONMENT.
Member Data Documentation
IModel slogo.backend.test.BackendTest.backend private
Definition at line 21 of file BackendTest.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/test/BackendTest.java