slogo_team03: slogo.backend.impl.parsing.GrammarRule Class Reference
slogo.backend.impl.parsing.GrammarRule Class Reference
Public Member Functions
GrammarRule (String command, String[] args)
GrammarRule (String command, List< String > args)
GrammarRule (String command[], String[][] args)
int matches (List< ISyntaxNode > nodes)
boolean infiniteMatchRecurse (List< List< String >> searchPattern, List< String > searchRemaining)
String toString ()
Private Member Functions
boolean infiniteMatches (List< List< String >> searchPattern, List< String > toSearch, int index)
Static Private Member Functions
static boolean isInfinite (List< List< String >> searchPattern)
Private Attributes
List< String > command
List< List< String > > args
Detailed Description
Definition at line 11 of file GrammarRule.java.
Constructor & Destructor Documentation
slogo.backend.impl.parsing.GrammarRule.GrammarRule (String command, String[] args)
Definition at line 15 of file GrammarRule.java.
References slogo.backend.impl.parsing.GrammarRule.command.
slogo.backend.impl.parsing.GrammarRule.GrammarRule (String command, List< String > args)
Definition at line 19 of file GrammarRule.java.
slogo.backend.impl.parsing.GrammarRule.GrammarRule (String command[], String args[][])
Definition at line 30 of file GrammarRule.java.
Member Function Documentation
boolean slogo.backend.impl.parsing.GrammarRule.infiniteMatches (List< List< String >> searchPattern, List< String > toSearch, int index) private
Definition at line 57 of file GrammarRule.java.
References slogo.backend.impl.parsing.GrammarRule.infiniteMatchRecurse().
Referenced by slogo.backend.impl.parsing.GrammarRule.matches().
boolean slogo.backend.impl.parsing.GrammarRule.infiniteMatchRecurse (List< List< String >> searchPattern, List< String > searchRemaining)
Definition at line 62 of file GrammarRule.java.
References slogo.Constants.INFINITE_MATCHING_LABEL, and slogo.backend.impl.parsing.GrammarRule.isInfinite().
Referenced by slogo.backend.impl.parsing.GrammarRule.infiniteMatches(), and slogo.backend.test.GrammarRuleTest.testInfiniteMatchRecurse().
static boolean slogo.backend.impl.parsing.GrammarRule.isInfinite (List< List< String >> searchPattern) static private
To check for infinite, if any of the possible matches is the infinite wildcard, then everything else will be ignored; i.e. don't include anything else if you include the infinite matching wildcard
Parameters
searchPattern The remaining pattern to search
Returns
Whether the second element contains the infinite matching wildcard
Definition at line 118 of file GrammarRule.java.
References slogo.Constants.INFINITE_MATCHING_LABEL.
Referenced by slogo.backend.impl.parsing.GrammarRule.infiniteMatchRecurse().
int slogo.backend.impl.parsing.GrammarRule.matches (List< ISyntaxNode > tokens)
Check if the rule matches any right subset of a list of tokens
Parameters
tokens The tokens to match on
Returns
The index indicating the beginning of the match; -1 if no match
Implements slogo.backend.parsing.IGrammarRule.
Definition at line 39 of file GrammarRule.java.
References slogo.backend.impl.parsing.GrammarRule.infiniteMatches().
String slogo.backend.impl.parsing.GrammarRule.toString ()
Definition at line 127 of file GrammarRule.java.
Member Data Documentation
List<List<String> > slogo.backend.impl.parsing.GrammarRule.args private
Definition at line 13 of file GrammarRule.java.
List<String> slogo.backend.impl.parsing.GrammarRule.command private
Definition at line 12 of file GrammarRule.java.
Referenced by slogo.backend.impl.parsing.GrammarRule.GrammarRule().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/parsing/GrammarRule.java