slogo_team03: slogo.backend.util.ITurtleStatus Interface Reference
slogo.backend.util.ITurtleStatus Interface Reference
Public Member Functions
List< ILine > lineSequence ()
ICoordinates turtlePosition ()
IDirection turtleDirection ()
PenState penState ()
Visibility turtleVisibility ()
Qualities turtleQualities ()
boolean isActive ()
void setActive (boolean b)
Detailed Description
The status of one turtle
Definition at line 11 of file ITurtleStatus.java.
Member Function Documentation
boolean slogo.backend.util.ITurtleStatus.isActive ()
Get whether the turtle is currently active, i.e. will respond to commands
Returns
Whether the turtle will respond to commands
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.UI.MethodRunner.changeTurtle(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), and slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw().
List<ILine> slogo.backend.util.ITurtleStatus.lineSequence ()
Get the sequence of lines that have been drawn so far
Returns
a list of lines, in order of drawing
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.UI.MethodRunner.moveTurtle(), and slogo.backend.test.OperationTest.testForward().
PenState slogo.backend.util.ITurtleStatus.penState ()
Get the state of the Pen
Returns
the state of the Pen
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.backend.impl.evaluation.commands.turtle.IsPenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.UI.MethodRunner.moveTurtle(), slogo.UI.MethodRunner.setPenState(), and slogo.backend.test.OperationTest.testForward().
void slogo.backend.util.ITurtleStatus.setActive (boolean b)
Set the turtle to be active or inactive
Parameters
true for active, false for inactive
Implemented in slogo.backend.impl.util.TurtleStatus.
IDirection slogo.backend.util.ITurtleStatus.turtleDirection ()
Get the direction of the turtle
Returns
the direction that the turtle is pointing
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.UI.MethodRunner.changeTurtle(), slogo.backend.impl.evaluation.commands.turtle.Heading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.UI.MethodRunner.setTurtleDirection(), and slogo.backend.test.OperationTest.testForward().
ICoordinates slogo.backend.util.ITurtleStatus.turtlePosition ()
Get the position of the turtle
Returns
the coordinates representing the position of the turtle
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.UI.MethodRunner.changeTurtle(), slogo.backend.impl.evaluation.commands.turtle.XCoordinate.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.YCoordinate.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), and slogo.backend.test.OperationTest.testForward().
Qualities slogo.backend.util.ITurtleStatus.turtleQualities ()
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.UI.MethodRunner.drawNewLine(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.HideTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ShowTurtle.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.UI.MethodRunner.setBackgroundColor(), slogo.UI.MethodRunner.setPenColor(), slogo.UI.MethodRunner.setPenThickness(), and slogo.UI.MethodRunner.setTurtleImage().
Visibility slogo.backend.util.ITurtleStatus.turtleVisibility ()
Get the state of the Turtle
Returns
the state of the turtle
Implemented in slogo.backend.impl.util.TurtleStatus.
Referenced by slogo.backend.impl.util.TurtleStatus.Builder.Builder(), slogo.backend.impl.evaluation.commands.turtle.IsShowing.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenUp.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetShape.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.PenDown.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetBackground.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenColor.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Home.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Right.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetHeading.executeRaw(), slogo.backend.impl.evaluation.commands.turtlestatus.SetPenSize.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetTowards.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Left.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.ClearScreen.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Backward.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.SetPosition.executeRaw(), slogo.backend.impl.evaluation.commands.turtle.Forward.executeRaw(), slogo.UI.MethodRunner.setTurtleVisibility(), and slogo.backend.test.OperationTest.testForward().
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/util/ITurtleStatus.java