slogo_team03: slogo.backend.util.ILine Interface Reference
slogo.backend.util.ILine Interface Reference
Public Member Functions
ICoordinates start ()
ICoordinates end ()
Visibility visible ()
Detailed Description
A directed line that is either visible or invisible
Definition at line 7 of file ILine.java.
Member Function Documentation
ICoordinates slogo.backend.util.ILine.end ()
Get the end of the line
Returns
coordinates representing the end of the line
Implemented in slogo.backend.impl.util.Line.
Referenced by slogo.UI.MethodRunner.drawNewLine(), slogo.UI.MethodRunner.redrawIfInScene(), and slogo.backend.test.OperationTest.testForward().
ICoordinates slogo.backend.util.ILine.start ()
Get the start of the line
Returns
coordinates representing the start of the line
Implemented in slogo.backend.impl.util.Line.
Referenced by slogo.UI.MethodRunner.drawNewLine(), slogo.UI.MethodRunner.redrawIfInScene(), and slogo.backend.test.OperationTest.testForward().
Visibility slogo.backend.util.ILine.visible ()
Get whether the line is visible or not
Returns
an enum representing whether the line is visible or not
Implemented in slogo.backend.impl.util.Line.
The documentation for this interface was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/util/ILine.java