slogo_team03: slogo.backend.impl.Backend Class Reference
slogo.backend.impl.Backend Class Reference
Public Member Functions
Backend () throws InitializationException
IExecutionContext execute (String string) throws ExecutionException
Private Member Functions
List< ITokenRule > tokenRules ()
List< IGrammarRule > grammarRules ()
Private Attributes
IExecutionContext lastContext
Tokenizer tokenizer
Parser parser
Evaluator evaluator
Detailed Description
Definition at line 29 of file Backend.java.
Constructor & Destructor Documentation
slogo.backend.impl.Backend.Backend () throws InitializationException
Definition at line 36 of file Backend.java.
References slogo.backend.impl.util.TurtleStatus.Builder.build(), slogo.Constants.DEFAULT_TURTLE_NAME, slogo.backend.impl.Backend.grammarRules(), and slogo.backend.impl.Backend.tokenRules().
Member Function Documentation
IExecutionContext slogo.backend.impl.Backend.execute (String string) throws ExecutionException
Execute a command
Parameters
string a string representing the command
Implements slogo.IModel.
Definition at line 147 of file Backend.java.
References slogo.backend.impl.evaluation.Evaluator.evaluate(), slogo.backend.impl.parsing.Parser.parse(), and slogo.backend.impl.tokenization.Tokenizer.tokenize().
List<IGrammarRule> slogo.backend.impl.Backend.grammarRules () private
Definition at line 64 of file Backend.java.
References slogo.Constants.CLOSING_LIST_LABEL, slogo.Constants.CONSTANT_LABEL, slogo.Constants.INFINITE_MATCHING_LABEL, slogo.Constants.OPENING_LIST_LABEL, and slogo.Constants.VARIABLE_LABEL.
Referenced by slogo.backend.impl.Backend.Backend().
List<ITokenRule> slogo.backend.impl.Backend.tokenRules () private
Definition at line 54 of file Backend.java.
References slogo.backend.impl.tokenization.TokenRule.Builder.build(), slogo.Constants.CLOSING_LIST_LABEL, slogo.Constants.COMMAND_LABEL, slogo.Constants.CONSTANT_LABEL, slogo.Constants.OPENING_LIST_LABEL, and slogo.Constants.VARIABLE_LABEL.
Referenced by slogo.backend.impl.Backend.Backend().
Member Data Documentation
Evaluator slogo.backend.impl.Backend.evaluator private
Definition at line 34 of file Backend.java.
IExecutionContext slogo.backend.impl.Backend.lastContext private
Definition at line 31 of file Backend.java.
Parser slogo.backend.impl.Backend.parser private
Definition at line 33 of file Backend.java.
Tokenizer slogo.backend.impl.Backend.tokenizer private
Definition at line 32 of file Backend.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/Backend.java