slogo_team03: slogo.UI.ListViewSLOGOVariables Class Reference
slogo.UI.ListViewSLOGOVariables Class Reference
Public Member Functions
ListViewSLOGOVariables (Group root)
ListViewSLOGOVariables (VBox vBox)
Public Member Functions inherited from slogo.UI.ListViewAllSLOGO
ListViewAllSLOGO (Group root)
ListViewAllSLOGO (VBox vBox)
ListViewAllSLOGO createListView (int listViewHeight, int listViewWidth, int vboxXpos, int vboxYpos, String labelName, int fontSize, Color color)
ListViewAllSLOGO createListView (int listViewHeight, int listViewWidth, String labelName, int fontSize, Color color)
Protected Member Functions
void create ()
Protected Member Functions inherited from slogo.UI.ListViewAllSLOGO
ListView< String > getListView ()
void setItems (ObservableList< String > oList)
ObservableList< String > getItems ()
abstract void create ()
Private Member Functions
void initializeVariablesMap ()
Private Attributes
ObservableList< String > myList
Additional Inherited Members
Protected Attributes inherited from slogo.UI.ListViewAllSLOGO
ListViewCreator myListViewCreator
Detailed Description
Definition at line 10 of file ListViewSLOGOVariables.java.
Constructor & Destructor Documentation
slogo.UI.ListViewSLOGOVariables.ListViewSLOGOVariables (Group root)
Definition at line 14 of file ListViewSLOGOVariables.java.
slogo.UI.ListViewSLOGOVariables.ListViewSLOGOVariables (VBox vBox)
Definition at line 18 of file ListViewSLOGOVariables.java.
Member Function Documentation
void slogo.UI.ListViewSLOGOVariables.create () protected
Definition at line 23 of file ListViewSLOGOVariables.java.
References slogo.UI.ListViewAllSLOGO.createListView(), slogo.UI.ListViewCreator.getListView(), slogo.UI.ListViewSLOGOVariables.initializeVariablesMap(), slogo.UI.AppConstants.LIST_BLOCKS_HEIGHT, slogo.UI.AppConstants.LIST_BLOCKS_WIDTH, and slogo.UI.ListViewAllSLOGO.myListViewCreator.
Referenced by slogo.UI.ModuleCreationHelper.createListViews().
void slogo.UI.ListViewSLOGOVariables.initializeVariablesMap () private
Definition at line 30 of file ListViewSLOGOVariables.java.
Referenced by slogo.UI.ListViewSLOGOVariables.create().
Member Data Documentation
ObservableList<String> slogo.UI.ListViewSLOGOVariables.myList private
Definition at line 12 of file ListViewSLOGOVariables.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/ListViewSLOGOVariables.java