slogo_team03: slogo.backend.impl.parsing.SyntaxNode Class Reference
slogo.backend.impl.parsing.SyntaxNode Class Reference
Public Member Functions
SyntaxNode (String type, IOperation operation, List< ISyntaxNode > children)
IOperation operation ()
List< ISyntaxNode > children ()
void setChildren (List< ISyntaxNode > children)
String type ()
String toString ()
Private Attributes
IOperation operation
List< ISyntaxNode > children
String type
Detailed Description
Definition at line 8 of file SyntaxNode.java.
Constructor & Destructor Documentation
slogo.backend.impl.parsing.SyntaxNode.SyntaxNode (String type, IOperation operation, List< ISyntaxNode > children)
Definition at line 14 of file SyntaxNode.java.
References slogo.backend.impl.parsing.SyntaxNode.children(), slogo.backend.impl.parsing.SyntaxNode.operation(), and slogo.backend.impl.parsing.SyntaxNode.type().
Member Function Documentation
List<ISyntaxNode> slogo.backend.impl.parsing.SyntaxNode.children ()
Get the children of this node
Returns
the node's children
Implements slogo.backend.parsing.ISyntaxNode.
Definition at line 26 of file SyntaxNode.java.
Referenced by slogo.backend.impl.parsing.SyntaxNode.setChildren(), and slogo.backend.impl.parsing.SyntaxNode.SyntaxNode().
IOperation slogo.backend.impl.parsing.SyntaxNode.operation ()
Get the operation associated with the node
Returns
the operation associated with the node
Implements slogo.backend.parsing.ISyntaxNode.
Definition at line 21 of file SyntaxNode.java.
Referenced by slogo.backend.impl.parsing.SyntaxNode.SyntaxNode().
void slogo.backend.impl.parsing.SyntaxNode.setChildren (List< ISyntaxNode > children)
Implements slogo.backend.parsing.ISyntaxNode.
Definition at line 31 of file SyntaxNode.java.
References slogo.backend.impl.parsing.SyntaxNode.children().
String slogo.backend.impl.parsing.SyntaxNode.toString ()
Definition at line 41 of file SyntaxNode.java.
References slogo.backend.impl.parsing.SyntaxNode.type().
String slogo.backend.impl.parsing.SyntaxNode.type ()
Get a name representing the child
Returns
the name
Implements slogo.backend.parsing.ISyntaxNode.
Definition at line 36 of file SyntaxNode.java.
Referenced by slogo.backend.impl.parsing.SyntaxNode.SyntaxNode(), and slogo.backend.impl.parsing.SyntaxNode.toString().
Member Data Documentation
List<ISyntaxNode> slogo.backend.impl.parsing.SyntaxNode.children private
Definition at line 11 of file SyntaxNode.java.
IOperation slogo.backend.impl.parsing.SyntaxNode.operation private
Definition at line 10 of file SyntaxNode.java.
String slogo.backend.impl.parsing.SyntaxNode.type private
Definition at line 12 of file SyntaxNode.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/parsing/SyntaxNode.java