slogo_team03: slogo.frontend.Config.ConfigHashMapCreator Class Reference
slogo.frontend.Config.ConfigHashMapCreator Class Reference
Public Member Functions
ConfigHashMapCreator ()
Map< String, String > getConfigHashMap ()
void setVariableMap (Map< String, String > map)
void setNumOfTurtles (int turtles)
void setColorParam (Color color, String name)
Private Member Functions
String fromIntToString (int i)
Private Attributes
Map< String, String > configMap
Map< String, String > variableMap
int numOfTurtles
Detailed Description
NOT FULLY IMPLEMENTED OR COMPLETED. NOT REPRESENTATIVE OF THE REST OF THE PROJECT
Author
Michael Deng
Definition at line 15 of file ConfigHashMapCreator.java.
Constructor & Destructor Documentation
slogo.frontend.Config.ConfigHashMapCreator.ConfigHashMapCreator ()
Definition at line 21 of file ConfigHashMapCreator.java.
Member Function Documentation
String slogo.frontend.Config.ConfigHashMapCreator.fromIntToString (int i) private
Definition at line 47 of file ConfigHashMapCreator.java.
Referenced by slogo.frontend.Config.ConfigHashMapCreator.setNumOfTurtles().
Map<String, String> slogo.frontend.Config.ConfigHashMapCreator.getConfigHashMap ()
Definition at line 25 of file ConfigHashMapCreator.java.
References slogo.frontend.Config.ConfigHashMapCreator.configMap.
Referenced by slogo.UI.ModuleCreationHelper.activateSaveButton().
void slogo.frontend.Config.ConfigHashMapCreator.setColorParam (Color color, String name)
Definition at line 42 of file ConfigHashMapCreator.java.
void slogo.frontend.Config.ConfigHashMapCreator.setNumOfTurtles (int turtles)
Definition at line 36 of file ConfigHashMapCreator.java.
References slogo.frontend.Config.ConfigHashMapCreator.fromIntToString().
Referenced by slogo.UI.ModuleCreationHelper.activateSaveButton().
void slogo.frontend.Config.ConfigHashMapCreator.setVariableMap (Map< String, String > map)
Definition at line 29 of file ConfigHashMapCreator.java.
Referenced by slogo.UI.ModuleCreationHelper.activateSaveButton().
Member Data Documentation
Map<String, String> slogo.frontend.Config.ConfigHashMapCreator.configMap private
Definition at line 17 of file ConfigHashMapCreator.java.
Referenced by slogo.frontend.Config.ConfigHashMapCreator.getConfigHashMap().
int slogo.frontend.Config.ConfigHashMapCreator.numOfTurtles private
Definition at line 19 of file ConfigHashMapCreator.java.
Map<String, String> slogo.frontend.Config.ConfigHashMapCreator.variableMap private
Definition at line 18 of file ConfigHashMapCreator.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/frontend/Config/ConfigHashMapCreator.java