slogo_team03: slogo.UI.VBoxCreator Class Reference
slogo.UI.VBoxCreator Class Reference
Public Member Functions
VBoxCreator (Group root)
VBoxCreator (HBox hBox)
VBox createVBox (int spacing, Integer x_Coord, Integer y_Coord)
VBox createVBox (int spacing)
VBox createVBoxScrollable (int spacing)
Private Attributes
Group root
HBox hBox
Detailed Description
10/14/2014
Version 1
Author
Michael Deng
Definition at line 17 of file VBoxCreator.java.
Constructor & Destructor Documentation
slogo.UI.VBoxCreator.VBoxCreator (Group root)
The Constructor
Parameters
root The group of the scene
Definition at line 27 of file VBoxCreator.java.
References slogo.UI.VBoxCreator.root.
slogo.UI.VBoxCreator.VBoxCreator (HBox hBox)
The Constructor
Parameters
hBox An HBox
Definition at line 36 of file VBoxCreator.java.
References slogo.UI.VBoxCreator.hBox.
Member Function Documentation
VBox slogo.UI.VBoxCreator.createVBox (int spacing, Integer x_Coord, Integer y_Coord)
Creates a VBox
Parameters
spacing The spacing between each module in the VBox
x_Coord The x pos of the VBox
y_Coord The y pos of the YBox
Returns
The newly created VBox
Definition at line 48 of file VBoxCreator.java.
Referenced by slogo.UI.ModuleCreationHelper.createDebugVBox(), slogo.UI.ModuleCreationHelper.createPauseButton(), slogo.UI.ModuleCreationHelper.createPlayButton(), slogo.UI.ModuleCreationHelper.createResetButton(), and slogo.UI.ModuleCreationHelper.createStopButton().
VBox slogo.UI.VBoxCreator.createVBox (int spacing)
Creates a VBox
Parameters
spacing The spacing between the modules
Returns
The newly created VBox
Definition at line 67 of file VBoxCreator.java.
VBox slogo.UI.VBoxCreator.createVBoxScrollable (int spacing)
Creates a VBox that is scrollable
Parameters
spacing The spacing between the modules
Returns
The newly created VBox
Definition at line 85 of file VBoxCreator.java.
Referenced by slogo.UI.ModuleCreationHelper.createListVBox(), and slogo.UI.ModuleCreationHelper.createSelectorVBox().
Member Data Documentation
HBox slogo.UI.VBoxCreator.hBox private
Definition at line 20 of file VBoxCreator.java.
Referenced by slogo.UI.VBoxCreator.VBoxCreator().
Group slogo.UI.VBoxCreator.root private
Definition at line 19 of file VBoxCreator.java.
Referenced by slogo.UI.VBoxCreator.VBoxCreator().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/VBoxCreator.java