slogo_team03: slogo.UI.ListViewCreator Class Reference
slogo.UI.ListViewCreator Class Reference
Public Member Functions
ListViewCreator (int height, int width)
ListViewCreator ()
Protected Member Functions
ListView< String > getListView ()
VBox createListViewWithLabel (String s, int fontsize, Color color)
Private Attributes
ListView< String > myListView
Detailed Description
Definition at line 8 of file ListViewCreator.java.
Constructor & Destructor Documentation
slogo.UI.ListViewCreator.ListViewCreator (int height, int width)
Definition at line 12 of file ListViewCreator.java.
slogo.UI.ListViewCreator.ListViewCreator ()
Definition at line 18 of file ListViewCreator.java.
Member Function Documentation
VBox slogo.UI.ListViewCreator.createListViewWithLabel (String s, int fontsize, Color color) protected
Definition at line 26 of file ListViewCreator.java.
References slogo.UI.LabelCreator.createLabel().
Referenced by slogo.UI.ListViewAllSLOGO.createListView().
ListView<String> slogo.UI.ListViewCreator.getListView () protected
Definition at line 22 of file ListViewCreator.java.
References slogo.UI.ListViewCreator.myListView.
Referenced by slogo.UI.ListViewSLOGOVariables.create(), slogo.UI.ListViewAllSLOGO.getItems(), slogo.UI.ListViewAllSLOGO.getListView(), and slogo.UI.ListViewAllSLOGO.setItems().
Member Data Documentation
ListView<String> slogo.UI.ListViewCreator.myListView private
Definition at line 10 of file ListViewCreator.java.
Referenced by slogo.UI.ListViewCreator.getListView().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/ListViewCreator.java