slogo_team03: slogo.backend.impl.parsing.Parser Class Reference
slogo.backend.impl.parsing.Parser Class Reference
Public Member Functions
Parser (List< IGrammarRule > rules) throws InvalidGrammarRuleException
void loadGrammar (List< IGrammarRule > rules) throws InvalidGrammarRuleException
ISyntaxNode parse (List< IToken > tokens) throws MalformedSyntaxException
List< ISyntaxNode > tokensToNodes (List< IToken > tokens) throws MalformedSyntaxException
Private Member Functions
String dereference (String element)
int hasProduction (List< ISyntaxNode > nodeStack)
List< ISyntaxNode > reduce (List< ISyntaxNode > nodes, int index)
ISyntaxNode createNestedNode (List< ISyntaxNode > nodes)
String generateParseErrorMessage (List< ISyntaxNode > all, List< ISyntaxNode > remaining)
Private Attributes
List< IGrammarRule > rules
IOperationFactory operationFactory
Detailed Description
Definition at line 23 of file Parser.java.
Constructor & Destructor Documentation
slogo.backend.impl.parsing.Parser.Parser (List< IGrammarRule > rules) throws InvalidGrammarRuleException
Definition at line 28 of file Parser.java.
References slogo.backend.impl.parsing.Parser.loadGrammar().
Member Function Documentation
ISyntaxNode slogo.backend.impl.parsing.Parser.createNestedNode (List< ISyntaxNode > nodes) private
Definition at line 130 of file Parser.java.
References slogo.Constants.CONSTANT_LABEL, and slogo.backend.parsing.ISyntaxNode.setChildren().
Referenced by slogo.backend.impl.parsing.Parser.reduce().
String slogo.backend.impl.parsing.Parser.dereference (String element) private
Definition at line 92 of file Parser.java.
References slogo.backend.impl.Languages.returnMap().
Referenced by slogo.backend.impl.parsing.Parser.tokensToNodes().
String slogo.backend.impl.parsing.Parser.generateParseErrorMessage (List< ISyntaxNode > all, List< ISyntaxNode > remaining) private
Definition at line 143 of file Parser.java.
Referenced by slogo.backend.impl.parsing.Parser.parse().
int slogo.backend.impl.parsing.Parser.hasProduction (List< ISyntaxNode > nodeStack) private
Definition at line 109 of file Parser.java.
Referenced by slogo.backend.impl.parsing.Parser.parse().
void slogo.backend.impl.parsing.Parser.loadGrammar (List< IGrammarRule > rules) throws InvalidGrammarRuleException
Implements slogo.backend.parsing.IParser.
Definition at line 34 of file Parser.java.
References slogo.backend.impl.parsing.Parser.rules.
Referenced by slogo.backend.impl.parsing.Parser.Parser().
ISyntaxNode slogo.backend.impl.parsing.Parser.parse (List< IToken > tokens) throws MalformedSyntaxException
Implements slogo.backend.parsing.IParser.
Definition at line 43 of file Parser.java.
References slogo.backend.impl.parsing.Parser.generateParseErrorMessage(), slogo.backend.impl.parsing.Parser.hasProduction(), slogo.backend.impl.parsing.Parser.reduce(), and slogo.backend.impl.parsing.Parser.tokensToNodes().
Referenced by slogo.backend.impl.Backend.execute(), slogo.backend.test.ParsingTest.testInvalidCommand(), slogo.backend.test.ParsingTest.testParse(), and slogo.backend.test.ParsingTest.testUnparseableCommand().
List<ISyntaxNode> slogo.backend.impl.parsing.Parser.reduce (List< ISyntaxNode > nodes, int index) private
Definition at line 119 of file Parser.java.
References slogo.backend.impl.parsing.Parser.createNestedNode().
Referenced by slogo.backend.impl.parsing.Parser.parse().
List<ISyntaxNode> slogo.backend.impl.parsing.Parser.tokensToNodes (List< IToken > tokens) throws MalformedSyntaxException
Definition at line 62 of file Parser.java.
References slogo.Constants.CLOSING_LIST_LABEL, slogo.Constants.CONSTANT_LABEL, slogo.backend.impl.parsing.Parser.dereference(), slogo.backend.evaluation.IOperationFactory.makeElement(), slogo.Constants.OPENING_LIST_LABEL, slogo.backend.impl.evaluation.commands.Operation.type(), and slogo.Constants.VARIABLE_LABEL.
Referenced by slogo.backend.impl.parsing.Parser.parse(), and slogo.backend.test.ParsingTest.testTokenToNode().
Member Data Documentation
IOperationFactory slogo.backend.impl.parsing.Parser.operationFactory private
Definition at line 26 of file Parser.java.
List<IGrammarRule> slogo.backend.impl.parsing.Parser.rules private
Definition at line 25 of file Parser.java.
Referenced by slogo.backend.impl.parsing.Parser.loadGrammar().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/backend/impl/parsing/Parser.java