slogo_team03: slogo.UI.Turtle Class Reference
slogo.UI.Turtle Class Reference
Public Member Functions
Turtle (String s, double x, double y, String id)
boolean isActive ()
void setColor (Color value)
Color getColor ()
void setLineProperty (String property)
Protected Member Functions
double getXPos ()
double getImageXPos ()
double getImageYPos ()
double getYPos ()
void setOrientation (double o)
void incrementOrientation (int o)
double getOrientation ()
void setImage (String name, Group root)
String getImageName ()
Node getImage ()
void moveTurtle (double d, double e)
Turtle getTurtle ()
Map< String, Image > getShapesMap ()
void setShapesMap (Map< String, Image > map)
void activate ()
void deactivate ()
String getLineProperty ()
int getThickness ()
void setThickness (int i)
String getId ()
void addLabel (Group root)
void removeLabel (Group root)
Private Member Functions
void activateTurtle ()
Map< String, String > initialImagesMap ()
void generateSelectorMap (Map< String, String > fileList)
void setXPos (double d)
void setYPos (double e)
Private Attributes
Node turtleImage
double xpos
double ypos
double orientation
Map< String, Image > imagesMap
Color color
int thickness
boolean active
String lineProperty
String imageName
String myId
Label myLabel
Detailed Description
10/10/2014
Version 1
Author
Michael Deng
Definition at line 23 of file Turtle.java.
Constructor & Destructor Documentation
slogo.UI.Turtle.Turtle (String s, double x, double y, String id)
The constructor
Parameters
s The value of the image
x The x position of the turtle
y The y position of the turtle
id The id of the turtle
Definition at line 47 of file Turtle.java.
References slogo.UI.Turtle.activateTurtle(), slogo.UI.Turtle.generateSelectorMap(), slogo.UI.Turtle.initialImagesMap(), slogo.UI.Turtle.moveTurtle(), and slogo.UI.Turtle.setOrientation().
Member Function Documentation
void slogo.UI.Turtle.activate () protected
Sets the value of active to true
Definition at line 294 of file Turtle.java.
void slogo.UI.Turtle.activateTurtle () private
Activates the event handler on the turtle
Definition at line 68 of file Turtle.java.
References slogo.UI.Turtle.active.
Referenced by slogo.UI.Turtle.Turtle().
void slogo.UI.Turtle.addLabel (Group root) protected
Adds a label to the turtle image
Parameters
root The group the label will belong to
Definition at line 357 of file Turtle.java.
void slogo.UI.Turtle.deactivate () protected
Sets the value of active to false
Definition at line 301 of file Turtle.java.
void slogo.UI.Turtle.generateSelectorMap (Map< String, String > fileList) private
Generates the map for the turtle's images
Parameters
fileList The list of files for the images
Definition at line 96 of file Turtle.java.
References slogo.UI.AppConstants.MAX_NEW_IMAGE_HEIGHT, and slogo.UI.AppConstants.MAX_NEW_IMAGE_WIDTH.
Referenced by slogo.UI.Turtle.Turtle().
Color slogo.UI.Turtle.getColor ()
Gets the color of the turtle lines
Returns
The color of the turtle lines
Definition at line 287 of file Turtle.java.
References slogo.UI.Turtle.color.
String slogo.UI.Turtle.getId () protected
Sets the ID of the turtle
Returns
The turtle ID
Definition at line 348 of file Turtle.java.
References slogo.UI.Turtle.myId.
Node slogo.UI.Turtle.getImage () protected
Gets the image of the turtle
Returns
The image
Definition at line 226 of file Turtle.java.
References slogo.UI.Turtle.turtleImage.
Referenced by slogo.UI.MethodRunner.setTurtleVisibility().
String slogo.UI.Turtle.getImageName () protected
Gets the image name
Returns
The image name
Definition at line 217 of file Turtle.java.
References slogo.UI.Turtle.imageName.
Referenced by slogo.UI.MethodRunner.setTurtleImage().
double slogo.UI.Turtle.getImageXPos () protected
Gets the turtle image's x position
Returns
The image's x position
Definition at line 132 of file Turtle.java.
References slogo.UI.AppConstants.INITIAL_TURTLE_X_POS.
double slogo.UI.Turtle.getImageYPos () protected
Gets the turtle image's y position
Returns
The image's y position
Definition at line 141 of file Turtle.java.
References slogo.UI.AppConstants.INITIAL_TURTLE_Y_POS.
String slogo.UI.Turtle.getLineProperty () protected
Gets the line texture of the turtle's path
Returns
The line texture
Definition at line 310 of file Turtle.java.
References slogo.UI.Turtle.lineProperty.
Referenced by slogo.UI.MethodRunner.drawNewLine().
double slogo.UI.Turtle.getOrientation () protected
Gets the orientation of the turtle
Returns
The orientation
Definition at line 191 of file Turtle.java.
References slogo.UI.Turtle.orientation.
Map<String, Image> slogo.UI.Turtle.getShapesMap () protected
Gets the shape map of the turtle
Returns
The shape map
Definition at line 255 of file Turtle.java.
References slogo.UI.Turtle.imagesMap.
Referenced by slogo.UI.TurtleImageSelector.create().
int slogo.UI.Turtle.getThickness () protected
Gets the thickness of the path's lines
Returns
The thickness of the path
Definition at line 329 of file Turtle.java.
References slogo.UI.Turtle.thickness.
Referenced by slogo.UI.ModuleCreationHelper.activateIncreaseDecreaseButtons(), slogo.UI.MethodRunner.changeTurtle(), slogo.UI.MethodRunner.drawNewLine(), and slogo.UI.MethodRunner.setPenThickness().
Turtle slogo.UI.Turtle.getTurtle () protected
Gets the turtle itself
Returns
The turtle
Definition at line 246 of file Turtle.java.
double slogo.UI.Turtle.getXPos () protected
Gets the x position of the turtle
Returns
The x position
Definition at line 123 of file Turtle.java.
References slogo.UI.Turtle.xpos.
double slogo.UI.Turtle.getYPos () protected
Gets the y position of the turtle
Returns
The y position
Definition at line 162 of file Turtle.java.
References slogo.UI.Turtle.ypos.
void slogo.UI.Turtle.incrementOrientation (int o) protected
Increments the orientation of the turtle
Parameters
o The amount of incrementation
Definition at line 181 of file Turtle.java.
Map<String, String> slogo.UI.Turtle.initialImagesMap () private
Creates a map of images for the turtle
Returns
The map of images
Definition at line 82 of file Turtle.java.
Referenced by slogo.UI.Turtle.Turtle().
boolean slogo.UI.Turtle.isActive ()
The boolean value of the selected turtle
Returns
True if the turtle is selected
Definition at line 264 of file Turtle.java.
References slogo.UI.Turtle.active.
void slogo.UI.Turtle.moveTurtle (double d, double e) protected
Moves the turtle to a specified coordinate
Parameters
d The x value
e The y value
Definition at line 236 of file Turtle.java.
References slogo.UI.Turtle.setXPos(), and slogo.UI.Turtle.setYPos().
Referenced by slogo.UI.MethodRunner.moveTurtle(), slogo.UI.Turtle.setImage(), and slogo.UI.Turtle.Turtle().
void slogo.UI.Turtle.removeLabel (Group root) protected
Removes the label from the turtle's image
Parameters
root The group the label belongs to
Definition at line 366 of file Turtle.java.
void slogo.UI.Turtle.setColor (Color value)
Sets the color of the turtle lines
Parameters
value The color
Definition at line 277 of file Turtle.java.
Referenced by slogo.UI.MethodRunner.setPenColor().
void slogo.UI.Turtle.setImage (String name, Group root) protected
Sets the image of the turtle
Parameters
name The name of the image
root The group the image belongs to
Definition at line 201 of file Turtle.java.
References slogo.UI.AppConstants.MAX_NEW_IMAGE_HEIGHT, slogo.UI.AppConstants.MAX_NEW_IMAGE_WIDTH, and slogo.UI.Turtle.moveTurtle().
Referenced by slogo.UI.MethodRunner.setTurtleImage().
void slogo.UI.Turtle.setLineProperty (String property)
Gets the line's property of the turtle
Parameters
property The line property
Definition at line 319 of file Turtle.java.
Referenced by slogo.UI.PathTextureSelector.create().
void slogo.UI.Turtle.setOrientation (double o) protected
Sets the orientation of the turtle
Parameters
o The orientation
Definition at line 171 of file Turtle.java.
Referenced by slogo.UI.MethodRunner.setTurtleDirection(), and slogo.UI.Turtle.Turtle().
void slogo.UI.Turtle.setShapesMap (Map< String, Image > map) protected
Definition at line 268 of file Turtle.java.
Referenced by slogo.UI.MethodRunner.changeTurtle().
void slogo.UI.Turtle.setThickness (int i) protected
Sets the thickness of the path's lines
Parameters
i The thickness of the path
Definition at line 338 of file Turtle.java.
Referenced by slogo.UI.ModuleCreationHelper.activateIncreaseDecreaseButtons(), and slogo.UI.MethodRunner.setPenThickness().
void slogo.UI.Turtle.setXPos (double d) private
Sets the x position of the turtle
Parameters
d The x value
Definition at line 111 of file Turtle.java.
References slogo.UI.AppConstants.MAX_NEW_IMAGE_WIDTH.
Referenced by slogo.UI.Turtle.moveTurtle().
void slogo.UI.Turtle.setYPos (double e) private
Sets the turtle image's y position
Returns
The image's y position
Definition at line 150 of file Turtle.java.
References slogo.UI.AppConstants.MAX_NEW_IMAGE_HEIGHT.
Referenced by slogo.UI.Turtle.moveTurtle().
Member Data Documentation
boolean slogo.UI.Turtle.active private
Definition at line 33 of file Turtle.java.
Referenced by slogo.UI.Turtle.activateTurtle(), and slogo.UI.Turtle.isActive().
Color slogo.UI.Turtle.color private
Definition at line 30 of file Turtle.java.
Referenced by slogo.UI.Turtle.getColor().
String slogo.UI.Turtle.imageName private
Definition at line 35 of file Turtle.java.
Referenced by slogo.UI.Turtle.getImageName().
Map<String, Image> slogo.UI.Turtle.imagesMap private
Definition at line 29 of file Turtle.java.
Referenced by slogo.UI.Turtle.getShapesMap().
String slogo.UI.Turtle.lineProperty private
Definition at line 34 of file Turtle.java.
Referenced by slogo.UI.Turtle.getLineProperty().
String slogo.UI.Turtle.myId private
Definition at line 36 of file Turtle.java.
Referenced by slogo.UI.Turtle.getId().
Label slogo.UI.Turtle.myLabel private
Definition at line 37 of file Turtle.java.
double slogo.UI.Turtle.orientation private
Definition at line 28 of file Turtle.java.
Referenced by slogo.UI.Turtle.getOrientation().
int slogo.UI.Turtle.thickness private
Definition at line 31 of file Turtle.java.
Referenced by slogo.UI.Turtle.getThickness().
Node slogo.UI.Turtle.turtleImage private
Definition at line 25 of file Turtle.java.
Referenced by slogo.UI.Turtle.getImage().
double slogo.UI.Turtle.xpos private
Definition at line 26 of file Turtle.java.
Referenced by slogo.UI.Turtle.getXPos().
double slogo.UI.Turtle.ypos private
Definition at line 27 of file Turtle.java.
Referenced by slogo.UI.Turtle.getYPos().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/Turtle.java