slogo_team03: slogo.UI.Main Class Reference
slogo.UI.Main Class Reference
Public Member Functions
void start (Stage primaryStage)
Static Public Member Functions
static void main (String[] args)
Private Attributes
ModuleCreationHelper ModulePopulator
View view
Detailed Description
October 7th, 2014
Version 1
Author
Michael Deng
Nick Widmaier
Michael Ren
Eric Chen
Definition at line 21 of file Main.java.
Member Function Documentation
static void slogo.UI.Main.main (String[] args) static
Launches the application
Parameters
args
Definition at line 53 of file Main.java.
void slogo.UI.Main.start (Stage primaryStage)
Starts up the application
Definition at line 30 of file Main.java.
References slogo.UI.AppConstants.BACKGROUND_COLOR, slogo.UI.ModuleCreationHelper.createMainPageModules(), slogo.View.init(), slogo.View.initRunner(), slogo.UI.ModuleCreationHelper.setView(), slogo.UI.AppConstants.STAGE_HEIGHT, and slogo.UI.AppConstants.STAGE_WIDTH.
Referenced by slogo.UI.ModuleCreationHelper.activateExtraWorkspaceButton().
Member Data Documentation
ModuleCreationHelper slogo.UI.Main.ModulePopulator private
Definition at line 23 of file Main.java.
View slogo.UI.Main.view private
Definition at line 24 of file Main.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team03/repository/src/slogo/UI/Main.java